### ISSUE TITLE
Add an alert dialog to display game info before the start of each game.

### ISSUE THREAD

**Issue by anubhakushwaha** [systers/malaria-app-android#105]
The current version of the app doesn't gives info about the games incorporated .Create alert dialog boxes on clicking the games and add small descriptions about the respective games.

**Comment by saketkumar95** [comment]
Can i work on it?

**Comment by anubhakushwaha** [comment]
@saketkumar95 No,this issue is allocated for GCI (Google Code In -2016) for pre-university students.You can pick any other free issue.

**Comment by vickyjjj** [comment]
I will take this issue. Is there a preferred location to get my descriptions  of the game approved? (i.e. here, GCI task comments, or Slack)

**Comment by chhavip** [comment]
You can submit a link to a google doc containing the descriptions in the comments section on your gci instance of the task, that will help the mentors to provide live suggestions and comments and easier for you to edit too.

**Comment by vickyjjj** [comment]
Pull request #113 added.

**Comment by MKDEVELOPEMENT** [comment]
so someone has done this already?

**Comment by anubhakushwaha** [comment]
@MKDEVELOPEMENT No worries,you can work upon it provided we don't sense any plagiarism as GCI is very strict on these terms.

**Comment by InfernoCoder** [comment]
@anubhakushwaha Here's my [PR(#122)](https://github.com/systers/malaria-app-android/pull/122).

**Comment by anubhakushwaha** [comment]
Closing. Fixed via #262
