### ISSUE TITLE
Correct alignment of months name

### ISSUE THREAD

**Issue by anubhakushwaha** [systers/malaria-app-android#106]
Currently the months' names displayed in the last tab of Malaria Home Screen tend to overflow to next line in case of lack of space. Adjust name of month and progress bar as to fit in a single line or name of month in one line and progress in the next.

**Comment by InfernoCoder** [comment]
Hi, I fixed this issue for GCI [here](https://github.com/systers/malaria-app-android/pull/119).

**Comment by anubhakushwaha** [comment]
@chhavip @yatna I guess we can wrap up this issue via #108
