### ISSUE TITLE
App Crash if empty file path for Reminder tone

### ISSUE THREAD

**Issue by codingblazer** [systers/malaria-app-android#109]
App crashes if the file path is empty in SET REMINDER TONE as shown below -
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/13872065/20846466/c2189694-b8ef-11e6-9d1b-2d99940895d6.gif)

**Comment by codingblazer** [comment]
There should be a check on file path - It must not be empty (validation) and file selected is of audio type (verification).

**Comment by chhavip** [comment]
Sounds good! would you like to take it up?

**Comment by codingblazer** [comment]
@chhavip Yeah sure

**Comment by codingblazer** [comment]
Fixed #110

**Comment by chhavip** [comment]
Hey @codingblazer , thank you for the PR, the norm is to not close the issue until the PR is approved and merged so in future please wait for the same before closing an issue! Will review as soon as possible.

**Comment by codingblazer** [comment]
@chhavip Will keep it in mind in future. Thanks.
