### ISSUE TITLE
App crash in SecondAnalyticFragment

### ISSUE THREAD

**Issue by codingblazer** [systers/malaria-app-android#111]
App crashes if user opens the last month progress bar (December here) as shown below -

<img src="https://cloud.githubusercontent.com/assets/13872065/20860094/2d9e75a4-b996-11e6-87db-5b1691b77e11.gif" height="350" width="200">

**Comment by chhavip** [comment]
@codingblazer Please provide an analysis of why you feel this is so and how would you go about correcting the same.

**Comment by codingblazer** [comment]
@chhavip 
The bug occurs only when the month is December and because of below mistake -
`calendar.set(Calendar.MONTH,intmon+1);
 month = _calendar.get(Calendar.MONTH);`

Here, value of **intmon** is 11 for December and in **calendar.set()**, we are trying to set **intmon+1** i.e 12 which results in overflow and thus value set is 0 (instead of 12).
In next step, value of **month** becomes 0 (since we are using **calendar.get()** which returns last set value=0)
Now, throughout the program this value of **month** is being used and in code -
`int currentMonth = mm - 1;
 String currentMonthName = getMonthAsString(currentMonth);`
Here **currentmonth** becomes **-1** which is used inside **getMonthAsString()** method. This method uses **months[currentMonth]** which results in ArrayIndexOutOfBoundsException.

**Comment by codingblazer** [comment]
@chhavip 
Sorry if I am not clear with explanation but problem is travelling between many methods before reaching crash which makes it hard to explain.
Problem can be solved as follows -
`calendar.set(Calendar.MONTH,intmon); month = _calendar.get(Calendar.MONTH)+1;`

Can I make a PR ?

**Comment by chhavip** [comment]
@codingblazer Good enough explanation! Go ahead :)

**Comment by chhavip** [comment]
Fixed by #112. Closing.
