### ISSUE TITLE
Add actions in notification itself

### ISSUE THREAD

**Issue by vishwesh3** [systers/malaria-app-android#114]
It would be much better if we add "Not taken", "taken", and snooze button in the notification itself. As of now it is showing in dialog in activity.

Yes , I would like to work on this.

**Comment by vishwesh3** [comment]
@ankita-kalra @yatna Please review it.

**Comment by yatna** [comment]
@vishwesh3 You can go ahead with this. Just try to stick to the following-
1. Try to keep the UI of the notification similar to the trip reminder notification.
2. Pressing the taken/ not taken/ snooze button must dismiss the notification along with the background notification sound.
3. The notification must be fixed ie it can't be dismissed by left/ right swipe action.

**Comment by vishwesh3** [comment]
@yatna Ok. I will soon create PR.

**Comment by vishwesh3** [comment]
Created PR #116

**Comment by chhavip** [comment]
Closing this issue. @yatna, please create a new issue for the notification button display
