### ISSUE TITLE
Removal of HTTPAsyncTask class

### ISSUE THREAD

**Issue by yvsssantosh** [systers/malaria-app-android#118]
Since HTTPAsyncTask class is not used anywhere I think it can be removed

 @chhavip ,@ankita-kalra, @yatna
Kindly review so that i can go ahead with a PR

Thanks :)

**Comment by yatna** [comment]
@yvssantosh Yes, the HTTP Requests are now being made in the ServerRequests class. You can go ahead with a PR.

**Comment by yvsssantosh** [comment]
@yatna 
I've made a pull request
Kindly review :)

**Comment by yatna** [comment]
Issue fixed. @yvsssantosh close this issue.
