### ISSUE TITLE
Bug in RapidFire Game

### ISSUE THREAD

**Issue by sridharjajoo** [systers/malaria-app-android#123]
When someone chooses an answer from the list of 3 options then other buttons are still active . So the user will be able to click all the other options as well which creates many errors . Choosing options multiple times leads to skipping of subsequent questions.
@chhavip @ankita-kalra @yatna Can I work on it?

**Comment by yatna** [comment]
Nice catch @sridharjajoo. You can go ahead with this. Disable rest of the buttons when an option is chosen.

**Comment by sridharjajoo** [comment]
@yatna PS:I have made a pull request.Kindly review it.

**Comment by chhavip** [comment]
Closing as it is now fixed.
