### ISSUE TITLE
Bug in the RapidFireGame Timer

### ISSUE THREAD

**Issue by sridharjajoo** [systers/malaria-app-android#126]
While playing the quiz if we press the exit button the timer is stopped.A dialog box opens up which has two options OK and CANCEL. When the CANCEL button is pressed the game is resumed but the timer doesn't resume from the original time when it was stopped.
@chhavip Can i work on the issue?

**Comment by yatna** [comment]
@sridharjajoo Go ahead :+1:

**Comment by sridharjajoo** [comment]
@yatna I have a small doubt...where should I make the changes....on a separate branch originating from the master or on the previous branch where I had made the last commit?

**Comment by yatna** [comment]
Create it on the same branch, else both PRs will contradict each other. Or else once the PR gets merged pull changes to your local repo and then create a fresh branch from master.

**Comment by sridharjajoo** [comment]
@yatna I'll opt the standard way.As soon as my previous PR gets merged, I'll send another PR.

**Comment by chhavip** [comment]
Can work on this now.

**Comment by sridharjajoo** [comment]
@yatna @chhavip I have sent the PR . Kindly review it.

**Comment by chhavip** [comment]
Solved via #137
