### ISSUE TITLE
Add support for app Accessibility

### ISSUE THREAD

**Issue by riddhik84** [systers/malaria-app-android#129]
Provide android:contentDescription to user interface controls to support accessibility via talkback.

**Comment by InfernoCoder** [comment]
Done [here (#131)](https://github.com/systers/malaria-app-android/pull/131).

**Comment by yatna** [comment]
@riddhik84 Sorry, I missed this issue. 
Since, @InfernoCoder  has already sent a PR, so you can either send a fresh PR for yourself or else we can merge the existing PR. Your call.

**Comment by riddhik84** [comment]
@yatna I don't have PR for this issue. I have raised it for GCI task :)

**Comment by anubhakushwaha** [comment]
Closing.Fixed via #258
