### ISSUE TITLE
Issue related to PlanMyTrip Activity

### ISSUE THREAD

**Issue by sridharjajoo** [systers/malaria-app-android#130]
1) When the departure date or the arrival date is set to any past date , the trip reminder alarm is still generated which shouldn't happen. I propose that whenever the user sets such a date then immediately a TOAST Message should pop up reminding him to fill the future dates.

2) When the Trip Reminder alarm notification appears in the notification bar , it is unresponsive . It would be better if an intent is fired to the original activity.

3) It would be nice if the user gets to know his/her overall score which could be displayed in the achievement room.

**Comment by yatna** [comment]
1. You can fix this. Just setting the condition that departure date must be equal to or ahead of current date will work. Condition for arrival date to be ahead of departure date is already present.
2. I think the purpose of the reminder is just to remind the user about the trip, hence opening up the app isn't required. 
3. Actually we added this feature during the last GSoC, but it was removed later as the iOS and Android teams collectively agreed not to keep a single score but 3 scores for different category and not display them directly to the user. The scores are indirectly displayed as badges. To maintain consistency with the iOS version of the app, we would like to keep this the way it was agreed upon.
You can send the PR for the 1st point mentioned :+1:

**Comment by chhavip** [comment]
Solved via #137
