### ISSUE TITLE
In UserMedicineSettingsFragmentActivity, if time is not selected error message or a toast should be shown.

### ISSUE THREAD

**Issue by free4murad** [systers/malaria-app-android#132]
Currently - In `UserMedicineSettingsFragmentActivity` if the user doesn't enter time and presses `Done` the user cannot proceed further. This is because the button is disabled.

My suggestion - Enable the button. If the user doesn't enter the time a toast message asking him to do so will appear. Only when the user enters the time, he will be able to go further.

@chhavip @yatna Should I make a PR for this issue.

**Comment by yatna** [comment]
@free4murad I don't think this is really an issue. The design of the app is same for iOS and Android  and we try to keep it the same unless there is a bug .

**Comment by free4murad** [comment]
@yatna 
I agree that it's not actually an issue, but usually when a button is disabled the color of the button is faded to show that its disabled.
if the color is same then usually a toast or snackbar is shown to tell the user that the button is disabled.

**Comment by yatna** [comment]
@free4murad Yeah, the button should be faded. For now, make the 'Done' button faded if reminder time is not chosen i.e make it disabled. If  in future we switch to toasts or snackbar we will let you know.

**Comment by chhavip** [comment]
Fixed via #144
