### ISSUE TITLE
App crashes in SecondAnalyticsFragment Activity

### ISSUE THREAD

**Issue by sridharjajoo** [systers/malaria-app-android#134]
1)Reset the app
2) Go to the fragment_second_analytics_Screen and make sure neither of the (TAKEN) OR (NOT TAKEN)
 button is checked.

![screenshot_2016-12-19-18-41-21-618_com peacecorps malaria](https://cloud.githubusercontent.com/assets/20684618/21314052/f798ddfa-c61a-11e6-8cbf-3fc9ae7430e0.png)

3)Check any of the given mentioned progress bar and choose a date when the user has missed
 entering the medecine  ( I chose 2nd November).

![screenshot_2016-12-19-18-03-38-678_com peacecorps malaria](https://cloud.githubusercontent.com/assets/20684618/21314105/3e23aa48-c61b-11e6-95ba-a1b41b723636.png)

4)Now when the back button to move back to the previous activity and then again on pressing back there is some serious crash! and the app doesnt reopen again.

@yatna @chhavip Should I work on this issue?

**Comment by yatna** [comment]
@sridharjajoo First try to find the reason for the crash, then we will move ahead to fix it. Nice catch 👍

**Comment by codingblazer** [comment]
@sridharjajoo Have you solved it yet

**Comment by sridharjajoo** [comment]
@codingblazer I have solved it . I'll send a PR.

**Comment by chhavip** [comment]
Fixed via #155
