### ISSUE TITLE
In PlanMyTrip there are some bugs.

### ISSUE THREAD

**Issue by free4murad** [systers/malaria-app-android#135]
1. In location user can just enter spaces.
2. If the user marks the pills in the list but does not select any pill the reminder is set.
3. In packing list the user can add an item and put spaces there.

@chhavip @yatna Should I make a PR for this issue.

**Comment by chhavip** [comment]
Nice catches, can go ahead.

**Comment by anubhakushwaha** [comment]
Closing.Fixed via #136
