### ISSUE TITLE
Bug in MedicineStore activity.

### ISSUE THREAD

**Issue by free4murad** [systers/malaria-app-android#138]
Even if the user enters 0 for the number of medicines required, a mail or message asking for zero medicines is sent.

@chhavip @yatna Should I make a PR for this issue.

**Comment by yatna** [comment]
Go ahead 👍

**Comment by yatna** [comment]
@free4murad +1 for using regex.
@chhavip Looks good to me.

**Comment by chhavip** [comment]
Solved via #142
