### ISSUE TITLE
Reduce apk size.

### ISSUE THREAD

**Issue by free4murad** [systers/malaria-app-android#143]
We can reduce the apk size significantly by using vector drawables for small icons and reducing the image size using some software.
The image quality will be not be affected.

**Comment by free4murad** [comment]
I saw this in Goole youtube channel.
You can check - 
https://www.youtube.com/watch?v=wlFVIIstKmA

I think this will significantly reduce the APK size.

**Comment by yatna** [comment]
@free4murad Try it and let us know how much are you being able to reduce.

**Comment by free4murad** [comment]
@yatna 
This issue is different from issue #164 

Here I want to compress the size of PNGs and use vector drawables. 

Whereas in issue #164 I have used a gradle command which does not include unreferenced resources in the APK.
