### ISSUE TITLE
Re-Fetching of InfoHub data on orientation change

### ISSUE THREAD

**Issue by HimanshuS01** [systers/malaria-app-android#145]
Data related to malaria in terms of policies,side-effects,etc in information hub fetches again when we change our device orientation.

![](http://im2.ezgif.com/tmp/ezgif.com-9cbcf214ee.gif)

@chhavip @yatna @MeepyMay I have solved the issue,should I send PR?.Thanks.

**Comment by codingblazer** [comment]
@HimanshuS01 Actually, its happening with all of them in info hub. I found other problems too in landscape. (Going to make issue soon).

**Comment by HimanshuS01** [comment]
@codingblazer sure.

**Comment by yatna** [comment]
@codingblazer The app has not been checked for orientation changes. Hence, there are a lot of bugs involving orientation change. Keep searching. You can send a PR for this one.

**Comment by HimanshuS01** [comment]
@yatna @chhavip PR sent.Please review it. Thank you :)
