### ISSUE TITLE
App crashes in Rapid Fire

### ISSUE THREAD

**Issue by codingblazer** [systers/malaria-app-android#146]
If the orientation is changed while playing rapid fire game , then app crashes after sometime.
(You may exit the game or wait on rapid fire game itself, app will crash anyway)

Demo - [Crash Video](https://youtu.be/trW1_835G4Q)

I have solved this. Should I send a PR @chhavip @yatna?

**Comment by codingblazer** [comment]
**Reason** - When we change the orientation, normally Android destroys the portrait activity and creates a new one for landscape but this has one exception - If any thread or AsynchTask is active it is not destroyed. In this game, though portrait activity is destroyed but its Counter timer (thread) of portrait is still running in background and when game finishes, this timer tries to show dialog in its activity (portrait) which was already destroyed and can't be found and app crashes. (Since finish game dialog takes 30 sec (5 ques) crash happens so late).

**Comment by codingblazer** [comment]
@yatna Can I send PR for this  :)

**Comment by yatna** [comment]
Oh, sorry I missed this one . Since you are handing orientation changes in the PR for #147, include this in the same PR, since both are concerned with orientation change.
