### ISSUE TITLE
Rapid Fire Game State not maintained when change orientation

### ISSUE THREAD

**Issue by codingblazer** [systers/malaria-app-android#147]
When the orientation is changed in rapid fire game the following things happens -

1. Exit Dialog box if was opened, gets closed
2. Game over dialog if opened gets closed
3. Game restarts from begining - score, time , question all gone

I have solved this problem. Should I send PR. @chhavip @yatna

**Comment by codingblazer** [comment]
**Reason** - The activity is recreated in landscape when orientation is changed.
**What I have done** - I have used savedInstance to store the values - millisLeft (so that it can start from same time) , current question no. and current score which are used for initialization for newly created landscape activity.
For dialog I am using Window Manager which if attached to dialog doesn't  allow dialog to be killed. (Using Dialog Fragment will increase the code base)

**Comment by yatna** [comment]
@codingblazer Nice work. You can send a PR.

**Comment by chhavip** [comment]
Closing as fixed through #174
