### ISSUE TITLE
Myth vs Fact Mini game starts from beginning on orientation change

### ISSUE THREAD

**Issue by HimanshuS01** [systers/malaria-app-android#148]
When user plays Myth vs Fact mini game and on changing the device orientation suddenly ,the game starts from very the beginning.

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/18090596/21506136/d75b1164-cc93-11e6-925f-5bdbf8acb753.gif)

Reason being:Activity is recreating on changing the device orientation.

Fix:I have used  onSaveInstanceState() method for solving this issue.

@MeepyMay @yatna @chhavip  Can I send PR for the same?

**Comment by yatna** [comment]
@HimanshuS01 Yes, you can. Nice work.
