### ISSUE TITLE
MediaPlayer in InfoHub->PeaceCorpspolicy

### ISSUE THREAD

**Issue by sridharjajoo** [systers/malaria-app-android#149]
The mediaplayer keeps on playing in the Peace Corps Policy until it is finished even if we switch back to previous Activity .It would be better if the media stopped playing when we are no longer on that particular activity. This generally happens after we change the orientation and then the back button is pressed.
Should I send a PR?@yatna @chhavip

**Comment by yatna** [comment]
@sridharjajoo Yes, you can go ahead. Make sure the speech runs continuously without restarting even if orientation is changed in middle.

**Comment by chhavip** [comment]
Fixed via #171. Closing.
