### ISSUE TITLE
Plan My Trip Activity data is lost.

### ISSUE THREAD

**Issue by m-murad** [systers/malaria-app-android#150]
If we change the screen orientation, Plan My Trip loses all data except location.

Data like dates, packing list should also be saved on changing screen orientation.

@chhavip @yatna should I make a PR for this?

**Comment by yatna** [comment]
@free4murad  Yes, seems there are a lot of bugs involving orientation change. You can go ahead.

**Comment by mahikaw** [comment]
@free4murad are you still working on this?

**Comment by free4murad** [comment]
Yes

**Comment by mahikaw** [comment]
It has been almost a month since you posted this issue, in case, you're busy with something, I could take help you in solving it. @free4murad

**Comment by free4murad** [comment]
Actually I have made a PR which changes this very file, if I make a PR for
this now there will be a merge conflict.
Once my earliest PR is merged I will send a PR for this.

**Comment by mahikaw** [comment]
@free4murad you can make different branches for different issues. It will help in such situations. :)

**Comment by anubhakushwaha** [comment]
@free4murad Working on this?

**Comment by free4murad** [comment]
@anubhakushwaha
I am travelling for a week or two. Please assign this to someone else.

**Comment by geekanamika** [comment]
We can close this issue for now as layouts for landscape screen are not available, app is restricted to portrait mode only.
