### ISSUE TITLE
Some changes needed in Manifest.xml

### ISSUE THREAD

**Issue by free4murad** [systers/malaria-app-android#153]
There are following issues in manifest.xml
1. There are some lines of code in manifest.xml which are not being used. 
`android:versionCode="1"
    android:versionName="1.0" >
    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="19" />`
We Can remove these lines.

2. Android studio is showing a suggestion for `<Application>` tag that we make the app indexable by Google search. This can be add a url in the file. We can add the URL of You can read about it here - http://developer.android.com/training/app-indexing/deep-linking.html

@chhavip @yatna
Should I send a PR.

**Comment by yatna** [comment]
1. versionCode and versionName may be used in future when creating updates for the app. Min and target Sdk versions  too convey relevant information.
2. Making the app index-able can be a new feature, but currently we do not want to add anything entirely new, we are more concerned in fixing existing bugs and optimizing existing code. Maybe we can see this in future.

**Comment by chhavip** [comment]
@yatna , if this is not required at the moment, I would suggest closing the issue.

**Comment by yatna** [comment]
@chhavip Yes, I think this is not required at the moment.

**Comment by chhavip** [comment]
Closing.
