### ISSUE TITLE
data not taken if orientation is changed during initial setup .

### ISSUE THREAD

**Issue by vaibhavchellani** [systers/malaria-app-android#157]
when user starts to set up which medicine he takes ,and changes the orientation the app progresses to next activity without the user pressing done .

attaching screenshots below,
![image](https://cloud.githubusercontent.com/assets/19390504/21581604/680a0a4e-d05e-11e6-85aa-6d1aa41ae2af.png)

when orientation is changed it proceeds to next activity,without the data.

![image](https://cloud.githubusercontent.com/assets/19390504/21581610/a17dc84c-d05e-11e6-823f-7aa836172495.png)

can i work on this ?

**Comment by yatna** [comment]
@vaibhavchellani This is being considered in PR #133 . You can close this issue.
