### ISSUE TITLE
bug in setup screen

### ISSUE THREAD

**Issue by vaibhavchellani** [systers/malaria-app-android#158]
The app proceeds to next activity without the user pressing done if the data fields are filled ,then app is closed and restarted .
I think that user should be able to proceed only after he presses done .
Method to recreate: open app->enter details->close app without pressing done ->open app again

can i work on this ?

**Comment by yatna** [comment]
This is already being fixed in #133. You can close this issue.

**Comment by vaibhavchellani** [comment]
oh , i somehow missed that one
