### ISSUE TITLE
media player keeps playing even when app is closed

### ISSUE THREAD

**Issue by vaibhavchellani** [systers/malaria-app-android#159]
the media player keeps on playing even when app is closed when the following steps are done when on infohub->peacecorps activity is opened and talkback is enabled,
change orientation->home button pressed 

i dont know if issue #149 will be considered the same as this one so i created a new one ,sincere apologies if the issue is considered to be same .

**Comment by yatna** [comment]
@vaibhavchellani Yes, this issue is more or less the same as #149. No problems, its good that you are going   through the previous issues before opening a new issue. However, you may want to close this one.
