### ISSUE TITLE
share dialogue box pops up when the button says email

### ISSUE THREAD

**Issue by vaibhavchellani** [systers/malaria-app-android#160]
In the tab Medicine Store ,when clicked on the button Order Medicine a dialogue box opens which asks for no of medicines and has 2 buttons Email and Message .Attaching screenshot,

![image](https://cloud.githubusercontent.com/assets/19390504/21582649/11211faa-d087-11e6-8676-466850300f46.png)

The issue is when Email button is pressed the pop-up appears which usually appears when share button is pressed .I think when email button is clicked the gmail app should open .

can i work on  it ?

**Comment by free4murad** [comment]
@vaibhavchellani
Gmail is not the only mailing application.
The user may be using some other application.

I suggest on clicking email, pop-up showing just email apps should appear.

**Comment by vaibhavchellani** [comment]
yes,actually i meant apps like gmail and other email apps should be shown not whatsapp ,facebook and other social apps .
thanks for correcting !

**Comment by yatna** [comment]
@vaibhavchellani Your argument seems valid. How do you intend to select only the 'mailing' type of applications?

**Comment by vaibhavchellani** [comment]
@yatna I think this provides a solution http://stackoverflow.com/questions/3312438/how-to-open-email-program-via-intents-but-only-an-email-program ,also i have posted some queries in the slack channel please see . Thank you

**Comment by yatna** [comment]
Yes, the first solution to the question is short and apt. I guess that will work. Go ahead.

**Comment by vaibhavchellani** [comment]
yeah i am on it !

**Comment by anubhakushwaha** [comment]
@vaibhavchellani Updates?

**Comment by vaibhavchellani** [comment]
yes , actually i had solved the issue and tried sending a PR ,but because .gitignore was not working the .idea files also got commited . I just found a solution to that problem and will be sending a PR within 2 days to all the issues.
Sincere apologies for the delay caused .

**Comment by vaibhavchellani** [comment]
im having issues creating a pull request .
@anubhakushwaha  if you could step by step guide me it would be very helpful for me .
Thank you !

**Comment by free4murad** [comment]
@vaibhavchellani 
What issue are you facing.
I can help.

**Comment by free4murad** [comment]
Is it the multiple commits??

**Comment by vaibhavchellani** [comment]
No , actually I cloned the forked repository and it contains only the master branch .  How to fetch all branches ?

**Comment by free4murad** [comment]
@vaibhavchellani 
It has all the branches. You are only seeing local branches.
To see all branches
Open the project in android studio.
I bottom right corner you will see git: master
click on that, select a remote branch the select checkout as new local branch

**Comment by free4murad** [comment]
![screen shot 2017-01-25 at 11 30 58 pm](https://cloud.githubusercontent.com/assets/17262180/22302792/6c318524-e356-11e6-8306-036f7d78242b.png)

![screen shot 2017-01-25 at 11 31 24 pm](https://cloud.githubusercontent.com/assets/17262180/22302796/70e549fc-e356-11e6-9f95-670a48a322bc.png)

**Comment by free4murad** [comment]
@vaibhavchellani 
Hope this helps.

**Comment by vaibhavchellani** [comment]
Yes it does . 
I have a habit of using the terminal and git branch showed only master .

**Comment by vaibhavchellani** [comment]
@free4murad  thank you for your help :)

**Comment by yatna** [comment]
@vaibhachellani To view all the branches form terminal use git branch -a

**Comment by anubhakushwaha** [comment]
Closing.Fixed #220
