### ISSUE TITLE
Dialogue box disappears when orientation changed

### ISSUE THREAD

**Issue by vaibhavchellani** [systers/malaria-app-android#162]
when the user navigates to the activity (attaching screenshot), clicks on edit and then changes the orientation without pressing okay  the dialogue box disappears. I think this should be fixed.Also the toast message appears again when orientation is changed. I would like to work on it , if permitted.

![image](https://cloud.githubusercontent.com/assets/19390504/21604025/fb651cc0-d1c6-11e6-9e64-2229ef6a6200.png)
 

![image](https://cloud.githubusercontent.com/assets/19390504/21604103/51e909d0-d1c7-11e6-8a5a-d8e63fc5a2c5.png)

**Comment by yatna** [comment]
Yes go ahead :+1:

**Comment by HimanshuS01** [comment]
@yatna actually there are also some other bugs related to device orientation.I will update it soon.Thanks

**Comment by vaibhavchellani** [comment]
should i send a PR ?
or are Orientation issues in hold?

**Comment by geekanamika** [comment]
App is restricted to potrait mode now due to unavailability of landscape layouts. Dialogs works as expected, closing this issue.
