### ISSUE TITLE
Reducing AKP size using gradle.

### ISSUE THREAD

**Issue by free4murad** [systers/malaria-app-android#164]
We can reduce the APK size by setting `shrinkResources` property to true in build.gradle file of the app.
By using this android studio will not include the unused resources and assets that are not referenced to in the code.

**Comment by free4murad** [comment]
@chhavip @yatna
I am making a PR for this.

**Comment by yatna** [comment]
Hey, you have already created an issue for this. Please, do not create duplicate issue. You can close this issue.

**Comment by yatna** [comment]
#143

**Comment by anubhakushwaha** [comment]
Closing.Fixed via #165
