### ISSUE TITLE
Bug in rapid fire game 

### ISSUE THREAD

**Issue by vaibhavchellani** [systers/malaria-app-android#169]
In the Rapid Fire game ,if the user clicks on exit button , the timer stops which is exactly what should be happening.A dialogue box pops up having 2 buttons exit and cancel .
The issue is if the user clicks cancel the game continues with the timer paused .
I would like to resolve this issue.

**Comment by HimanshuS01** [comment]
Hey @vaibhavchellani This issue has already been created  in #126 .Please close this issue.Thanks. :)
