### ISSUE TITLE
Bug in text to speech in PeaceCorpsPolicy

### ISSUE THREAD

**Issue by sridharjajoo** [systers/malaria-app-android#182]
**Issue**
When any external media is played in the background and at the same time if text to speech is played,, both of them will play simultaneously which needs attention.

**Solution**
It can be solved using Audiofocus.

@yatna @chhavip Should I send a PR?

**Comment by yatna** [comment]
@sridharjajoo Yes , go ahead. Also make sure tts stops(canceled) when the app goes out of focus, as currently it keeps on playing even if the app is closed. If possible try to stop/resume tts in case of calls and notifications.

**Comment by geekanamika** [comment]
Infohub is not receiving data from network, we can open this issue later.
