### ISSUE TITLE
Bug in PlanMytrip Activity

### ISSUE THREAD

**Issue by sridharjajoo** [systers/malaria-app-android#183]
**Issue**
In the packaging list option the dialog box appears only when we tap on the hint i.e "ADD ITEMS" . The dialog box should appear when we tap on any area of the view .

**Solution**
Just need to change the layout_height and layout_width to "match parent" .

@yatna @chhavip Should I send a P.R ?

**Comment by yatna** [comment]
@sridharjajoo Yup, go ahead.

**Comment by anubhakushwaha** [comment]
Closing.Fixed via #184
