### ISSUE TITLE
Bug in UserProfile activity.

### ISSUE THREAD

**Issue by free4murad** [systers/malaria-app-android#186]
When we open UserProfile activity the age field has value zero in it. We should remove this value as it hides the hint and user has to delete this to enter new age.

@yatna @chhavip 
Should I make a PR?

**Comment by chhavip** [comment]
Yes, go ahead

**Comment by free4murad** [comment]
@chhavip 
Should I close this issue?

**Comment by anubhakushwaha** [comment]
Closing.Fixed via #195
