### ISSUE TITLE
A toast reporting the error should be raised on the SetUp Screen

### ISSUE THREAD

**Issue by BaaniLeen** [systers/malaria-app-android#189]
![screenshot from 2017-01-09 07-15-46](https://cloud.githubusercontent.com/assets/22029744/21755541/8f0335c0-d63b-11e6-9387-86e184659a14.png)
In case the user does not choose a "Remind me at" time, and clicks on the done button, a Toast should be raised prompting the user about the error (eg. Please pick a suitable time for the reminder).
@yatna @chhavip Shall I send a PR?

**Comment by free4murad** [comment]
@BaaniLeen
I suggest this a some days back, but @yatna didn't approve. 

Instead she asked me to fade the button until time has not been selected.
PR #144 has been made by me for the same.

**Comment by yatna** [comment]
@BaaniLeen Sorry but, this issue has been solved already. Please close this issue and keep searching for new issues.

**Comment by BaaniLeen** [comment]
@yatna Sure maam... Thank you :)
