### ISSUE TITLE
.gitignore not working

### ISSUE THREAD

**Issue by mahikaw** [systers/malaria-app-android#190]
The gitignore is not working. This is leading to tracking unnecessary build files. This is increasing the size of the repo and everyone has to manually remove them before commiting.

@yatna @chhavip @MeepyMay can I make a PR to fix the same?

**Comment by chhavip** [comment]
@mahikaw Please wait for approval before sending a PR. They will not be reviewed if haven't been approved before.

**Comment by mahikaw** [comment]
@chhavip I had opened this issue in the power up repo too and it had been approved there, so I assumed it would be necessary to add here as well.
 I created the PR just to speed up the process. :)

**Comment by yatna** [comment]
@mahikaw Please wait till your issue gets assigned to you, as there are unassigned issues which were opened before your issue and it would be unfair to others that we review your PR before theirs.

**Comment by mahikaw** [comment]
@yatna , Okay. I'll take care of that. :)

**Comment by DipanshKhandelwal** [comment]
@prachi1210 I guess it can be closed.

**Comment by geekanamika** [comment]
@manishakeim @niksj It can be closed. .gitignore works perfectly now.

**Comment by m-murad** [comment]
@geekanamika 
the `.gitignore` file needs to be updated. Can you please do that.
Here is the recommended `gitignore` file for Android projects.

https://github.com/github/gitignore/blob/master/Android.gitignore
