### ISSUE TITLE
Generation of dialog box on Back Pressing from MythFact and RapidFire game

### ISSUE THREAD

**Issue by HimanshuS01** [systers/malaria-app-android#191]
**Current Behaviour**
Presently dialog box is generated when the user press an exit button in MythvsFact and RapidFire  game 
to exit from the game.

**Actual Behaviour**
Normally dialog box can also be generated on back pressing from the MythFactGame and RapidFireGame
activities like in other applications.

@chhavip @yatna  can I go ahead and send the PR If this is an intented enhancement ?Thanks.

**Comment by yatna** [comment]
@HimanshuS01 No, currently we do not need this enhancement. The back button is disabled currently so the user can exit using the exit button only.
You may close this issue.
