### ISSUE TITLE
Widgets are not updated when changes are made

### ISSUE THREAD

**Issue by free4murad** [systers/malaria-app-android#192]
The state of the widgets is not updated instantly when changes are made.
eg hwhe we change trip details the widget still shows the old details.

@chhavip @yatna
I am making a PR for this.

**Comment by yatna** [comment]
@free4murad Widgets are updated after 30 min of making a change. The limit is 30 mins because reducing it further adversely increases the battery drainage and is not recommended by google too.

**Comment by free4murad** [comment]
@yatna 
i agree about the minimum limit, what I am suggesting is if the user changes the details of the trip the widget will show the old data for another 30 mins.
Instead we can update the widget once the user updates the trip details.

there is no need to update the widget every 30mins. Instead we can update the widget only when trip details are changed.

**Comment by yatna** [comment]
@free4murad Okay, fine. Do it for both the widgets.

**Comment by chhavip** [comment]
Closing as PR has been merged.
