### ISSUE TITLE
PlanMyTrip active should show the details of currently planned trips.

### ISSUE THREAD

**Issue by free4murad** [systers/malaria-app-android#193]
When we open the plan my trip activity, the fields are blank.
Instead the fields should be populated the details of currently planned trip.
Same should be the case when the activity is opened using widget.

@chhavip @yatna
I am making a PR for this

**Comment by chhavip** [comment]
@free4murad, please get your issues approved before making a PR. A certain amount of discussion is required before you should begin working on an issue.

**Comment by free4murad** [comment]
Yes,
I am waiting for your approval.

**Comment by yatna** [comment]
@free4murad yes you can go ahead.

**Comment by anubhakushwaha** [comment]
Closing.Fixed via #209
