### ISSUE TITLE
Landscape UI Problems

### ISSUE THREAD

**Issue by codingblazer** [systers/malaria-app-android#196]
In landscape mode, there are some problems as follows -

1. Text not completely inside the box in MythGame as shown -

![whatsapp image 2017-01-12 at 21 14 31 1](https://cloud.githubusercontent.com/assets/13872065/21898460/f8006352-d912-11e6-97d6-a25d26a57b69.jpeg)

2. Done button in Setup Screen is cutting and not fully inside as shown -

![whatsapp image 2017-01-12 at 21 14 31](https://cloud.githubusercontent.com/assets/13872065/21898472/fd5cce26-d912-11e6-8482-0215188b27b2.jpeg)

3. The UI should be in center in following -

![whatsapp image 2017-01-12 at 21 14 31 3](https://cloud.githubusercontent.com/assets/13872065/21898518/1738732c-d913-11e6-92b2-f0b4b5fd81d0.jpeg)

4. Adding Scrollview at screens wherever not present.

@chhavip @yatna Should I send PR for this ? Thanks :-)

**Comment by anubhakushwaha** [comment]
@codingblazer Incase of fragment_second_analytic_screen.xml it is intended to be left aligned to leave space for graphview

**Comment by codingblazer** [comment]
@anubhakushwaha Is it intended for future ?

**Comment by anubhakushwaha** [comment]
@codingblazer Sorry I didn't get you,the graphview will be updated as per the progress of the user,it's initially not present due to insufficient data but if you try editing previous dates so as to have some data the graph is plotted,I hope I was able to clear else please let me know what exactly you are asking and further in that case the main mentors could also guide you properly.

**Comment by codingblazer** [comment]
@anubhakushwaha Yeah, I got you. Actually, graphview was not showing when data was less. Now it's visible. Thanks, I am removing this point from the issue. :-)

**Comment by chhavip** [comment]
@codingblazer Go ahead.

**Comment by codingblazer** [comment]
@chhavip Sure

**Comment by anubhakushwaha** [comment]
Closing.Fixed via #212
