### ISSUE TITLE
App showing Progress bar for future months

### ISSUE THREAD

**Issue by codingblazer** [systers/malaria-app-android#199]
**Current** - In Second Analytics Screen, the progress bar for old months - Dec, Nov, Oct opens Calendar for Dec 2017, Nov 2017 etc 
**Expected** - It should open Dec 2016 , Nov 2016 etc.

@chhavip @yatna Should I send PR for this?

**Comment by codingblazer** [comment]
@yatna I think this issue has been left. Please review :-)

**Comment by codingblazer** [comment]
@yatna @chhavip @anubhakushwaha Can i work on this ?

**Comment by anubhakushwaha** [comment]
@codingblazer Could you please report the cause of this bug before implementing it.

**Comment by anubhakushwaha** [comment]
@codingblazer Any updates?

**Comment by anubhakushwaha** [comment]
@codingblazer Are you working on this?

**Comment by codingblazer** [comment]
Really sorry for missing this, i wasn't getting notifications for this project. Yes, I will work on this soon after exams :-)

**Comment by codingblazer** [comment]
@anubhakushwaha The reason for the bug is as follows - In ThirdAnalyticFragment.java, year shown is always taken as the current year. This particular case was left out i.e. When current month is Jan/Feb/March then previous months will be from not the current year.

Solution - I will add a **if condition** handling this left out case. @anubhakushwaha Should I send PR for it ?

**Comment by anubhakushwaha** [comment]
@codingblazer  Yes go ahead

**Comment by geekanamika** [comment]
Issue is handled in PR #370 
Closing this issue.
