### ISSUE TITLE
Wrong information shared through achievements room.

### ISSUE THREAD

**Issue by top-gun007** [systers/malaria-app-android#203]
**Summary**
When the user navigates to achievement room and clicks on the share button the following text is shared.
 
![image](https://cloud.githubusercontent.com/assets/15179401/21937399/57286f62-d9dd-11e6-829f-29d4217e9cbc.png)

**Comment by yatna** [comment]
@top-gun007 Can you be more specific as which part of info you find wrong. I guess you are referring to the name, right?

**Comment by top-gun007** [comment]
Yes I was referring to the name.

**Comment by top-gun007** [comment]
@yatna please review this issue too https://github.com/systers/malaria-app-android/issues/198

**Comment by top-gun007** [comment]
@yatna, @anubhakushwaha can I proceed with this.

**Comment by free4murad** [comment]
@top-gun007 
i reported the same issue in #185 
was asked to leave the message as it is

**Comment by top-gun007** [comment]
thanks @free4murad
