### ISSUE TITLE
PeaceCorps logo disappears on changing the orientation

### ISSUE THREAD

**Issue by HimanshuS01** [systers/malaria-app-android#205]
**Current Behaviour**
PeaceCorps Logo in the Initial SetUp screen disappears on changing the device orientation.

![ezgif com-optimize 4](https://cloud.githubusercontent.com/assets/18090596/21954398/7736c1d0-da75-11e6-95a1-24867043b24c.gif)

**Expected Behaviour**
State of the Logo must be preserved (i.e. at the bottom right ) even after changing the device orientation.

@chhavip @yatna Can I send PR for this ? Thanks.

**Comment by yatna** [comment]
@HimanshuS01 This problem has been reported and assigned in a previous issue. Please close this one.
