### ISSUE TITLE
Bug in User Profile 

### ISSUE THREAD

**Issue by shyamsunder007** [systers/malaria-app-android#207]
1)The problem in the user profile is that if i write my age as any multiple zero digits (more than one). for example if i type "00" and click on save button then  it is not showing any type of warning about this but it is getting saved.
2)I think instead of getting saved it should throw a warning about it.
3)Can i proceed my work on this issue and i think i will be able to complete it as soon as possible
@chhavip @yatna Can I send PR for the same ? 
![screenshot_2017-01-15-04-25-24](https://cloud.githubusercontent.com/assets/16396376/21958741/1e5ab48e-dadb-11e6-9628-787a5a3e6d03.png)

**Comment by free4murad** [comment]
@shyamsunder007
While solving issue #186, I solved this as well.
You can check PR #195

**Comment by shyamsunder007** [comment]
Tqu murad,
but can i keep a limit for the age till 150 or 100 and can i PR on this.
@chhavip @yatna
