### ISSUE TITLE
Scrolling issue in TripIndicatorPackingDialog in Landscape mode

### ISSUE THREAD

**Issue by HimanshuS01** [systers/malaria-app-android#208]
**Current Behaviour**
 ListView for the **Packing Items**  dialog  is not scrollable in **Landscape** mode.

![ezgif com-optimize 5](https://cloud.githubusercontent.com/assets/18090596/22012574/bb3d39bc-dcba-11e6-80f6-88c4ef49fb73.gif)

**Expected Behaviour**
List for the packing items in TripIndicatorPackingActivity must be scrollable even in the landscape mode.

**Fix**
We can add a touch listener to Parent's ScrollView  that disables the parent's touch intercept when a touch starts in the child(ListView in our case), and then enables it back when the touch starts in the parent  again,
so that separate scrolling can occur easily in the parent's view as well as in the child view.

@chhavip @yatna I have a fix for this.Can I send PR for the same? Thanks :)

**Comment by HimanshuS01** [comment]
@chhavip @yatna @anubhakushwaha If this is a valid issue can I work on this? Thanks :)

**Comment by chhavip** [comment]
Yes, sounds like a good issue, can work on fixing it.

**Comment by HimanshuS01** [comment]
@chhavip sure. 👍

**Comment by anubhakushwaha** [comment]
Closing.Fixed via #228
