### ISSUE TITLE
 Problems with back button

### ISSUE THREAD

**Issue by ShailyTyagi** [systers/malaria-app-android#211]
Current action: Even if the user is not on the home screen ,on pressing the back buton ,it closes the app instead of taking the user to the previous screen .
![2017_01_22_10_20_51](https://cloud.githubusercontent.com/assets/18248854/22180142/de5812ce-e08d-11e6-842d-5a77cd38b7ad.gif)

Expected : If the user is o home screen ,it should close the app .Otherwise it should bring the user back to the previous screen.
Yes, i am more than happy to work if it is approved.

**Comment by anubhakushwaha** [comment]
@ShailyTyagi  Good catch but this has been implemented as a GCI task via #139 .Closing this issue hence,try finding more :)
