### ISSUE TITLE
landscape mode

### ISSUE THREAD

**Issue by mahikaw** [systers/malaria-app-android#214]
In "plan my trip" activity, if after choosing departure and arrival dates, we rotate the device, all of it gets reset.

![device-2017-01-22-162030](https://cloud.githubusercontent.com/assets/21010060/22181987/53585314-e0bf-11e6-90c8-96dd1da26604.png)

![device-2017-01-22-162052](https://cloud.githubusercontent.com/assets/21010060/22181990/87869286-e0bf-11e6-9ef4-d694f5b64adc.png)

@chhavip @yatna can I make a PR to fix this?

**Comment by free4murad** [comment]
@mahikaw 
this is a duplicate issue.
Already reported in #150.

**Comment by mahikaw** [comment]
closing.
