### ISSUE TITLE
App appearance issues

### ISSUE THREAD

**Issue by mahikaw** [systers/malaria-app-android#215]
The icons of "plan my trip", "info hub" and "user profile"  at the bottom are of a different colour as compared to the rest of the app's elements. 

![device-2017-01-22-160903](https://cloud.githubusercontent.com/assets/21010060/22182012/ff480c3c-e0bf-11e6-9196-b8e193895fdb.png)

Also, in the Home Screen, the existence of other activities by swipe isn't very obvious to the user because a light colour is used at the bottom(which isn't very visible in contrast to the background). I suggest we change it to a darker colour.

![device-2017-01-22-161011](https://cloud.githubusercontent.com/assets/21010060/22182054/48bdba6e-e0c1-11e6-8b00-3359bcd1de10.png)

@chhavip @yatna, Can I send a PR to fix this?

**Comment by anubhakushwaha** [comment]
@mahikaw Yes please proceed,further attach screenshots in your PR.

**Comment by anubhakushwaha** [comment]
@mahikaw Updates?

**Comment by anumehaagrawal** [comment]
Is this issue completed ? Can I take it up?

**Comment by geekanamika** [comment]
@m-murad @saurabhjn76 I would like to work on this issue.

**Comment by geekanamika** [comment]
App is currently using bottom navigation, closing this issue.
