### ISSUE TITLE
App crashes for high numerical values.

### ISSUE THREAD

**Issue by free4murad** [systers/malaria-app-android#216]
The app crashes if we enter high numerical values.
This can be seen in following places
1. `Age` in `UserProfile`.
![age](https://cloud.githubusercontent.com/assets/17262180/22186983/7da2781a-e124-11e6-9971-193cc63a0d8b.png)
2. `Settings` dialog box in `Medicine Store`.
![settings](https://cloud.githubusercontent.com/assets/17262180/22186984/87fb6d3a-e124-11e6-97f8-7a113bf64e7d.png)
3.  `Add Medicine to Store` dialog box in `Medicine Store`. (Already reported in issue # 197 )
![add medicine](https://cloud.githubusercontent.com/assets/17262180/22186985/8ee1d328-e124-11e6-957e-9b22391c6043.png)

@chhavip @yatna
I would like to work to correct first two.
Also if you could tell me what range should be permitted the above text fields.

**Comment by HimanshuS01** [comment]
hey @free4murad  if you don't mind can I solve the second one along with  my issue no. #197 as these dialogs are in the same activity(Medicine Store) and just require  a few line of code. Thanks :)

**Comment by free4murad** [comment]
@HimanshuS01 
Sure, no issue.

**Comment by anubhakushwaha** [comment]
Closing.Fixed via #239
