### ISSUE TITLE
In PlanMyTrip a user can select previous dates.

### ISSUE THREAD

**Issue by free4murad** [systers/malaria-app-android#217]
Current behaviour - The user while planning a trip can select days which have already passed.

Expected behaviour - All the previous dates should not be available to the user. The departure date can be any day after the current date. Also the arrival date should be after departure date.

@yatna @chhavip @anubhakushwaha
Should I make a PR.

**Comment by anubhakushwaha** [comment]
@free4murad It has been resolved via #137

**Comment by free4murad** [comment]
@anubhakushwaha 
I am suggesting something like this. Here the future dates are not avalible for selection
![screenshot_20170125-224520](https://cloud.githubusercontent.com/assets/17262180/22301315/a2683030-e350-11e6-8e7b-aa533f14723f.png)

Currently previous dates are available to be selected. But on selecting the previous dates the user gets a toast.
I suggest disabling the previous dates.

**Comment by anubhakushwaha** [comment]
@yatna @chhavip What do you think ?

**Comment by yatna** [comment]
@free4murad Yes, you can go ahead.

**Comment by chhavip** [comment]
Closing this issue as it has been resolved.
