### ISSUE TITLE
No error message displayed asking the user to enter the time at setup

### ISSUE THREAD

**Issue by nitish1211** [systers/malaria-app-android#222]
I think there should be a Toast or a SnackBar displayed when there is incomplete entering of data asking the user to fill up the missing field. Also changing the color of the text red on pressing of the done button seems like a good way of getting the user's attention to the required field.

Currently:
![g_20170126_1215393](https://cloud.githubusercontent.com/assets/13676490/22322952/5b20e2ba-e3c5-11e6-8506-230bfb9c34e0.gif)

What I am proposing:

![g_20170126_1242156](https://cloud.githubusercontent.com/assets/13676490/22323070/29d4eeb2-e3c6-11e6-829e-23cfc16a2c84.gif)

@anubhakushwaha @chhavip Can I send a PR for this?

**Comment by free4murad** [comment]
@nitish1211 
I already reported this issue here - #132 
And have solved it here - #144

**Comment by anubhakushwaha** [comment]
Done similar functionality via #144 . Closing.
