### ISSUE TITLE
Strings should be stored in resources(R.strings) and typo in Toast message

### ISSUE THREAD

**Issue by nitish1211** [systers/malaria-app-android#223]
The strings for the messages in the toasts are hard-coded but they should be stored in the `strings.xml` file. I would like to move a lot of these strings in toast messages and other locations to `strings.xml` . This would make the code cleaner.
It would be on similar lines to #47 
Also there is a typo in one of the toast messages:
Here it should be `"Reminder time missing"`

![g_20170126_1320153](https://cloud.githubusercontent.com/assets/13676490/22323790/20cc1656-e3cb-11e6-9c0f-d11293fbb083.gif)

@anubhakushwaha @chhavip Can I send a quick PR for this one?

**Comment by anubhakushwaha** [comment]
Yes you can go ahead but make sure to give meaningful string names so that each toast is easily identifiable while any kind of modification in future and yes you can correct the typo.Before you send a PR please mention which all toasts you refer to.

**Comment by chhavip** [comment]
@nitish1211 Updates?

**Comment by nitish1211** [comment]
Sent the PR. @chhavip

**Comment by geekanamika** [comment]
Duplicate issue.
