### ISSUE TITLE
Overdraw in app

### ISSUE THREAD

**Issue by m-murad** [systers/malaria-app-android#224]
There is some overdraw in the app.
Should I send a PR for this issue.

**Comment by anubhakushwaha** [comment]
@free4murad How are you planning to do it? By removing unnecessary backgrounds?

**Comment by free4murad** [comment]
@anubhakushwaha 
yes,
also i am through google docs to check for other ways.

**Comment by yatna** [comment]
@free4murad Please elaborate the issue. Mention what problems are occurring due to overdraw and how those can be overcome.

**Comment by free4murad** [comment]
@yatna 
overdraw causes performance and battery issues.
Overdraw basically is when GPU draws a single pixel multiple times. eg
![overdraw](https://cloud.githubusercontent.com/assets/17262180/22406919/35d5c5ce-e682-11e6-8edc-610e56b0830e.png)
here if complete cards are been drawn but only part of the cards are shown this is overdraw.
It will cost extra and useless GPU computation and battery.

**Comment by top-gun007** [comment]
Painters Algorithm right @free4murad

**Comment by anubhakushwaha** [comment]
@free4murad Any further update? did you get something?

**Comment by free4murad** [comment]
Will send a PR for this today.
