### ISSUE TITLE
User should be prompted

### ISSUE THREAD

**Issue by dilpreet96** [systers/malaria-app-android#225]
**Current behaviour**

On starting app ,user is asked to setup a reminder.
If Done Button is clicked without selecting a time no prompt appears to select the timings.

<img src="http://i.giphy.com/l3q2KHa2QGrTnfm3m.gif" /><br>

**Expected behaviour**
User should be prompted to select timings if he/she directly clicks on "Done" Button.

Should I send a PR for this issue?

**Comment by vaibhavchellani** [comment]
I think this issue was created(#132) and closed .

**Comment by anubhakushwaha** [comment]
It has always been resolved via #144 
Closing.
