### ISSUE TITLE
App crash on SecondAnalyticalFragmentActivity

### ISSUE THREAD

**Issue by yatna** [systers/malaria-app-android#23]
When the current date is between months January to April, the application crashes on the SecondAnalyticalFragmentActivity. When the current date is between month May to November the application works fine. When the month is December the app does not crash on the SecondAnalyticalFragmentActivity but crashes on clicking the December progress bar in the ThirdAnalyticalFragmentActivity.java .

**Comment by AM1A** [comment]
Tried resolving it,created a pull request.

**Comment by ankita-kalra** [comment]
@AM1A  attach short clip from the app showing status of issue.

**Comment by haddada** [comment]
@ankita-kalra  is this issue still open ?

**Comment by ankita-kalra** [comment]
resolved #32
