### ISSUE TITLE
App crashes in UserProfile Activity.

### ISSUE THREAD

**Issue by m-murad** [systers/malaria-app-android#231]
In user profile activity if we change the device orientation when the user details are being saved, the app crashes.

@yatna @chhavip @anubhakushwaha 
Should I send a PR.

**Comment by yatna** [comment]
@free4murad Yes, you can go ahead.

**Comment by pragyach** [comment]
If this issue is not assigned to any one shall i make Pr to solve it?
@yatna @chhavip  @anubhakushwaha

**Comment by HimanshuS01** [comment]
hey @pragyach This issue has already been solved by @free4murad in PR #235 . :)
you can pick any other unassigned issues labeled as free or can create a new one . Thanks

**Comment by geekanamika** [comment]
Closing it & solving as a part of #334
