### ISSUE TITLE
Back button closes the application.

### ISSUE THREAD

**Issue by free4murad** [systers/malaria-app-android#232]
In activities like 
1. `MainActivity`
2. `UserProfile`
3. `NewHomeActivity`
4. `TripIndicatorFragmentActivity`
5. `InfoHubFragmentActivity`

the back button closes the app instead of going back to previous activity.

@chhavip @yatna @anubhakushwaha 
Should i send a PR.

**Comment by yatna** [comment]
@free4murad I think this issue has already been made multiple times already in the past #211 #166 #213

**Comment by free4murad** [comment]
@yatna 
But this hasn't been solved.

**Comment by anubhakushwaha** [comment]
@free4murad #139 was done as a part of GCI.
