### ISSUE TITLE
Fresh developer 

### ISSUE THREAD

**Issue by mani94454182** [systers/malaria-app-android#233]
Hello
I'm a new developer and I want to contribute to your project as it seemed to be very interesting.
I ensure you that once it get comfortable and gain enough knowledge in your work, I will give my 100% to work for it
I'm waiting for a chance to prove myself capable
Hoping to get a chance this time
thanking you

**Comment by codingblazer** [comment]
@mani94454182 Welcome to the community. Issue list is only for project related issues. You can join [Slack](https://systers-opensource.slack.com/) channel. Thanks :-)

**Comment by HimanshuS01** [comment]
@mani94454182 welcome to this organisation. Pick any [issue](https://github.com/systers/malaria-app-android/issues) marked as free from the given issue list and feel free to ask any kind of doubts whether in the comment section of any issue or in the slack channel. cheers 👍

**Comment by anamikalovesSRK** [comment]
how can i join Slack channel of this project ?  I can't figure it out

**Comment by codingblazer** [comment]
https://systers-opensource.slack.com/?redir=%2Fmessages%2F%40slackbot%2F

**Comment by anamikalovesSRK** [comment]
well, by saying how to join, i meant how to contact team administrator as i am not part of this slack team yet. There is no such link to message/pm/email team administrator. Thanks :)

**Comment by anubhakushwaha** [comment]
@anamikalovesSRK @mani94454182 Welcome to Systers :) Here's the link for the invite http://systers.io/slack-systers-opensource/ ,please join the slack channels for the respective projects you are interested in and ask your queries there,any mentor who will be available will reach out to you.Further we don not appreciate pm until and unless important.
