### ISSUE TITLE
App Crashes in UserProfile Activity when age entered is out of int range

### ISSUE THREAD

**Issue by nitish1211** [systers/malaria-app-android#238]
There is no check for the age entered by the user in the profile section.
The app crashes when the age is out of the range supported by `int` .

![g_20170222_2104543](https://cloud.githubusercontent.com/assets/13676490/23219019/eec41b66-f943-11e6-8713-0677fd4d1eec.gif)

@anubhakushwaha @chhavip @yatna 
Should I send a PR for this?

**Comment by free4murad** [comment]
This has been reported earlier and I am working on this.

**Comment by free4murad** [comment]
Already reported in #216
