### ISSUE TITLE
Adjust icons to maintain consistent UI in UserMedicineSettingsFragmentActivity

### ISSUE THREAD

**Issue by pandilladivya** [systers/malaria-app-android#240]
In the Spinner( drop down ) , the icons are not scaled with respect to the text present beside them. 

UI would look better if the icons are adjusted to match the text's layout.

![screenshot_2017-03-07-23-05-46](https://cloud.githubusercontent.com/assets/16818129/23669915/f121c9a6-038b-11e7-9360-ed4ded2f372d.png)

@yatna @anubhakushwaha @chhavip
Kindly Review this issue.
Thanks :)

**Comment by pragyach** [comment]
This fixing this issue can result into more user friendly app, shall i fix this issue?  @anubhakushwaha  @chhavip

**Comment by pandilladivya** [comment]
@pragyach I've already solved this and am waiting for mentors to approve this issue..

**Comment by anubhakushwaha** [comment]
@pandilladivya Yes go ahead

**Comment by pandilladivya** [comment]
@anubhakushwaha  Will submit a PR soon.

Thank You :)

**Comment by anubhakushwaha** [comment]
Closing.Fixed via #247
