### ISSUE TITLE
Add a Graphical Representation in Volunteer Adherence Rate to maintain consistency in UI

### ISSUE THREAD

**Issue by BaaniLeen** [systers/malaria-app-android#241]
![17200601_436103846781687_1974123612_o](https://cloud.githubusercontent.com/assets/22029744/23688723/317a60b2-03dc-11e7-90cd-5cef7467beb2.png)
A Graphical Representation of the data will help maintain Consistency in UI as well as make it easier for the user to comprehend the facts .
@yatna @chhavip @anubhakushwaha Shall I make a PR for the same? :)

**Comment by top-gun007** [comment]
Currently I guess this repo is only dealing with bugs not improvements.

**Comment by BaaniLeen** [comment]
@yatna @chhavip Kindly review the issue... Thanks!

**Comment by DipanshKhandelwal** [comment]
@m-murad @saurabhjn76 can I take this up?

**Comment by geekanamika** [comment]
Info-hub is not receiving any data from network, we can open this issue later.
