### ISSUE TITLE
Bugs in TripIndicatorFragmentActivity

### ISSUE THREAD

**Issue by pandilladivya** [systers/malaria-app-android#242]
**The following the Bugs related to Departure and Arrival Dates in the TripIndicatorFragmentActivity**

- Departure and Arrival Dates cannot be the past date. But In the App there is no condition to check for that.

- Year field is taking negative values when the selected year is less than 2000.

![screenshot_2017-03-08-11-34-40](https://cloud.githubusercontent.com/assets/16818129/23692257/8557107e-03f3-11e7-83ee-1ad2e192ff1c.png)

**Demo** : https://pandilladivya.github.io/2017_03_08_01_26_53.mp4

@chhavip @ankita-kalra  @anubhakushwaha 
Kindly review the issue.
I would like to work on this.
Thank you :)

**Comment by free4murad** [comment]
I have submitted a PR for this earlier.

**Comment by pandilladivya** [comment]
@free4murad Can you please refer to the PR which you are mentioning here?

I have already gone through the issues and PRs .. but couldnt find the similar issue.

**Comment by pandilladivya** [comment]
@free4murad 
Pardon me ... I didnt notice.

I did not checkout the latest master branch.
