### ISSUE TITLE
Issue in TripIndicatorPackingActivity

### ISSUE THREAD

**Issue by pandilladivya** [systers/malaria-app-android#246]
Medicines and cash are not being added in the UI ( to the bottom)  whenever a user selects them but are added in the backend. Items are added when the user hits add icon ...... So it would create a confusion to the user whether medicines and cash are added to the selection or not.

Further, once the user is finished with his/her selection and want to change it then there's no way for the user to know what items have been added because opening that dialog usually opens the empty list'

Here's the demo of the issue recorded.
https://pandilladivya.github.io/2017_03_11_12_14_48.mp4

I would like to work on this issue.

@anubhakushwaha @chhavip @yatna 
Kindly Review this issue.
Thank You.

**Comment by geekanamika** [comment]
This issue has been resolved in updated `gsoc18-code` branch.
