### ISSUE TITLE
 UI Issues in PackingActivity

### ISSUE THREAD

**Issue by pandilladivya** [systers/malaria-app-android#248]
1.  Confusing UI . 
 
**Video Demo:**
https://pandilladivya.github.io/2017_03_11_12_25_03.mp4

Instead of making the text clickable in one row and making editText clickable in the other row, to make the View consistent we can make the Text clickable in all rows and lock the editText.
 

2.   AutoWrap the content in the EditText.

  ![screenshot_2017-03-11-17-12-28](https://cloud.githubusercontent.com/assets/16818129/23822983/0f702958-067e-11e7-851a-a7984737bfc0.png)

-  Cash can accommodate only 3 Digits.
 https://pandilladivya.github.io/2017_03_11_17_22_15.mp4

@anubhakushwaha @yatna @chhavip 
Kindly Review this issue.

**Comment by r00pal** [comment]
@haroonshah2764 you can take this up.

**Comment by haroonshah2764** [comment]
@roopalJazz 
sorry for the delay, i missed the comment.
