### ISSUE TITLE
Reminder tone doesn't get set to the new selected tone.

### ISSUE THREAD

**Issue by pandilladivya** [systers/malaria-app-android#249]
**Steps to Reproduce the Bug**

- Click on the Volume Button.

- Specify the path to the new tone

- Click Yes

Remainder Tone doesn't get set to the new tone.

@anubhakushwaha @ankita-kalra @chhavip 
Kindly Review this issue.
Thank you :)

**Comment by anubhakushwaha** [comment]
@pandilladivya Yes go ahead.

**Comment by HimanshuS01** [comment]
hey @pandilladivya updates ? Are you still working on it ? :-)

**Comment by pandilladivya** [comment]
oops!! .. I din't check this!

Will work on it from now on :slightly_smiling_face: 

@anubhakushwaha Thank you for Reviewing the issue... Will make a PR soon. :slightly_smiling_face:

**Comment by anubhakushwaha** [comment]
@pandilladivya Working on this?

**Comment by pandilladivya** [comment]
@anubhakushwaha 
Sorry ma'am .. Was tied up with my exams :(

**Comment by sammy1997** [comment]
Are you still working on this bug? @pandilladivya

**Comment by sammy1997** [comment]
I think line 51 in DrugReminderNotification is where the error lies.
@anubhakushwaha  mam can I work on this?

**Comment by anubhakushwaha** [comment]
@pandilladivya Incase you are not working on this should I assign it to @sammy1997 ?

**Comment by sammy1997** [comment]
@anubhakushwaha ma'am from the Slack mention, I am on it then.

**Comment by sammy1997** [comment]
@anubhakushwaha Ma'am the issue has been resolved. Do I send a PR to the develop branch?

**Comment by geekanamika** [comment]
Resolved in updated code, closing this issue.
