### ISSUE TITLE
Alarm Tone Doesn't Stop After Hitting Cancel In Reminder Dialog -Bug

### ISSUE THREAD

**Issue by adamfils** [systers/malaria-app-android#250]
**Expected Behaviour**
When you Click Cancel in the Alarm Dialogue it stop
Actual Behaviour
When you click "cancel" the dialogue closes but the Reminder Tone keeps playing even when you exit the app

I'd love to work on this 
I believe I can fix it
@yatna @chhavip @anubhakushwaha

**Comment by adamfils** [comment]
Expected Behaviour

When you Click Cancel in the Alarm Dialogue it stop

Actual Behaviour

When you click "cancel" the dialogue closes but the Reminder Tone keeps playing even when you exit the app

**Comment by sammy1997** [comment]
@adamfils @anubhakushwaha  is someone still working on this? Mam can you assign me this?
