### ISSUE TITLE
TTS service not stopped properly.

### ISSUE THREAD

**Issue by free4murad** [systers/malaria-app-android#252]
In `PeaceCorpsPolicyFragmentActivity` if the user has activated the TTS service and closes the app by pressing the recent apps button the TTS service continues running.

@chhavip @anubhakushwaha @yatna
Should I send a PR?

**Comment by HimanshuS01** [comment]
hey @free4murad this issue is a duplicate of #182 in which @yatna have already mentioned the above issue PR of which is already created. Kindly refer. Thanks :)

**Comment by free4murad** [comment]
@HimanshuS01
Thanks for pointing this out.
