### ISSUE TITLE
 show the data like medication taken on time, missed ones through visualization pie charts etc.

### ISSUE THREAD

**Issue by Rupinderwadali** [systers/malaria-app-android#260]
As we track the medicine taken on time or missed ones. We can show them through visualization like pie charts etc.

**Comment by Rupinderwadali** [comment]
Will also show the current users data for more interactivity

**Comment by anubhakushwaha** [comment]
@Rupinderwadali the current state of the app shows the adherence which is in way giving a stat of the past history in terms of medicine taken,further the calendar that comes on clicking the progress bar shows the days on which the medicines are taken with a green tick and not taken with a red one.Incase you still feel the need for adding a PieChart let us know with proper justification. It's like adding a completely new feature and hence will have to see the tradeoff between the necessary info being provided already to the user and incorporating a new way of giving the same information.

**Comment by anubhakushwaha** [comment]
Closing.Not taking it up as of now.
