### ISSUE TITLE
Add events through google calendar API

### ISSUE THREAD

**Issue by Rupinderwadali** [systers/malaria-app-android#261]
we can add the event of traveling or anything through google calendar API for reminder.

**Comment by anubhakushwaha** [comment]
@Rupinderwadali nice suggestion,how would you like to implement it?As in you shouldn;t change the functionality the trip feature provides.

**Comment by anubhakushwaha** [comment]
@Rupinderwadali Willing to have a discussion on this? as by going forward with this will change a lot in the codebase.

**Comment by luckyman000786** [comment]
@anubhakushwaha  Can I do it ?

**Comment by geekanamika** [comment]
We can open this issue later when bugs issues are resolved in project, this is low priority now.
