### ISSUE TITLE
Replaced Hardcore strings with strings resource

### ISSUE THREAD

**Issue by akashagra** [systers/malaria-app-android#270]
Hardcore string is used,which is not a good practice in add_medicine_dailog file and hence replaced withstring resource

**Comment by sammy1997** [comment]
I guess you can close this one. I have resolved this one in the along with https://github.com/systers/malaria-app-android/issues/249 . So I will send a PR.

**Comment by m-murad** [comment]
@sammy1997 
Issues are closed once concerned PRs are merged.

Also don't solve multiple issues in a single PR. This is not a good practice. Solve one issue per PR.
Also only solve the issue assigned to you.

**Comment by sammy1997** [comment]
@m-murad I will keep that in mind.

**Comment by sammy1997** [comment]
@anubhakushwaha  please assign this issue to  me.

**Comment by geekanamika** [comment]
Solved in #291
