### ISSUE TITLE
Updating Android API version and Android Studio 3.0 Compatibility

### ISSUE THREAD

**Issue by robillo** [systers/malaria-app-android#272]
### What is wrong?
Currently, the app gradle file for the project aims at Android API 22, which is version Lollipop. As per valid sources, the usage of the version Lollipop is less than 28% of all Android devices, so it is recommended to target latest Android versions. [refer here] (https://fossbytes.com/most-popular-android-versions-always-updated/).

### Expected behaviour.
What do you think should be the expected behaviour?
It is required to target latest Android version. Also, the introduction of latest version of Android Studio (3.0) expects to add a few lines of code integration for future enhancements. Moreover, it is always recommended to write down all app dependencies in the project level gradle file of the application for decent app scalability, which requires to be done.

### Screenshot or GIF
Screenshots:
![screen shot 2017-10-31 at 3 28 32 am](https://user-images.githubusercontent.com/19509186/32197897-09eb3b1e-bdec-11e7-80a8-3817daf2fa8f.png)
![screen shot 2017-10-31 at 3 28 19 am](https://user-images.githubusercontent.com/19509186/32197898-0a27fcd4-bdec-11e7-8a69-7a8e60473a8f.png)

### Do you want to work on the issue?
I would want to work on this issue.

**Comment by geekanamika** [comment]
@m-murad This  can be closed.
