### ISSUE TITLE
Code is not written properly, needs refractoring.

### ISSUE THREAD

**Issue by arya-ayush** [systers/malaria-app-android#277]
The coding architecture is failing at many places in the app.It is just making the code difficult to debug and manage. 

It should be refractored using some of the basic android libraries like ButterKnife, DaoDatabase and where ever model is merged with other codes should be re-written again i.e., MVC implementation.

Some of the issues are in naming conventions.

**Comment by arya-ayush** [comment]
I will do it,  if you allow.

**Comment by geekanamika** [comment]
@MeepyMay @anubhakushwaha this can be closed(or put open-later) as it involves development lifecycle.
