### ISSUE TITLE
User details not being saved

### ISSUE THREAD

**Issue by abhinavbajpai2012** [systers/malaria-app-android#280]
The user details filled is not saved and is erased whenever we move from that activity

Whenever we come back to the user activty it should show the saved data and an edit button can be added if user wants to change his/her details.

I want to work on this issue

**Comment by geekanamika** [comment]
@m-murad Can you please review this issue? I would like to implement it.
Shall i update the issue with gif if it's not clear ?

**Comment by geekanamika** [comment]
Agreed. Thank You. I'll save the details in sharedpreferences & create a PR if you'll approve.

**Comment by m-murad** [comment]
Sure send a PR

**Comment by Sudhanshu96** [comment]
@m-murad can I take up this issue?

**Comment by geekanamika** [comment]
Hi sudhanshu,  I accidentally deleted my previous comment. I am working on this issue after getting approved my mentor :)

**Comment by geekanamika** [comment]
Shifting it to MVP & value is being saved in preferences.
