### ISSUE TITLE
Update minimum and maximum target SDK versions

### ISSUE THREAD

**Issue by arundhati24** [systers/malaria-app-android#282]
### What is wrong?

Currently, the minimum target SDK version of the app is 9 and the maximum is 22, which covers only around 42.3% of the android devices.

### Expected behaviour.

The minimum target SDK should be 15 and the maximum target SDK should be 26 so that most of the app can run on maximum number of devices, including older devices as well. This will include around 99.7% of the android devices.  

### Screenshots

Please refer the following for more information : (taken from developer.android.com)

![pie_chart_target_devices](https://user-images.githubusercontent.com/30979369/37243286-027f01ae-249d-11e8-987c-64bd0e379759.png)

![stats_android_versions](https://user-images.githubusercontent.com/30979369/37243292-0e458c1a-249d-11e8-8a41-95c91937784c.png)

### Do you want to work on the issue?

Yes, I would like to work on this.

**Comment by geekanamika** [comment]
Similar to #272 , it already contains a PR. Don't create an issue if it's already present :)

**Comment by arundhati24** [comment]
@geekanamika  This only talks about the maximum sdk version. I had already checked it. :) 
I talked about minimum version too.

**Comment by arundhati24** [comment]
#272 doesn't talk about minimum sdk version. And, we aim to reach out to the maximum number of people but at the same time we also need to consider the functionality and technicalities of the app. A lot of features are deprecated with new APIs. So, I believe this needs to be considered. :smiley:

**Comment by geekanamika** [comment]
Hey @arundhati24  Yes the issue mentions targetSdkVersion only. But if you'll notice the screenshots/PR , it contains minSdkVersion as 16 ,which seems good to me.
