### ISSUE TITLE
Use Lombok to remove boilerplate code in models

### ISSUE THREAD

**Issue by arundhati24** [systers/malaria-app-android#283]
### What is wrong?

Currently, the Java classes in model directory have boilerplate code that leads to an unnecessary code in the class. This takes a little more time for any person, especially newcomers, to understand the code and keeping boilerplate code in a class is not considered a good practice either. 

### Expected behaviour.

The boilerplate code present in Java classes in model directory should be replaced using Lombok plugin. This would make the code a lot cleaner and easier to understand.

### Do you want to work on the issue?

Yes, I would like to work on this issue.

**Comment by geekanamika** [comment]
Including a dependency to reduce boilerplate code needs to be discussed properly,sounds good to me.  Going by the work-flow , Can you provide instance that it wouldn't effect the application size , it would help in maintaining code ?

**Comment by geekanamika** [comment]
We have entity classes as suggested by Room guidelines. We can close this issue, Please create another issue if you find bugs or discuss in #malaria Slack channel.
