### ISSUE TITLE
Use Room for fluent database access

### ISSUE THREAD

**Issue by arundhati24** [systers/malaria-app-android#284]
### What is wrong?

Currently, there is a lot of boilerplate code needed to handle database. We need to write and analyze a lot of code for simple database operations. This increases the complexity of the work and it is a tedious task for the contributors to go through the code to understand it. 

### Expected behaviour.

Now, we have the official Android library called Room that can help structure our database and make it much more convenient to use. We need not write a lot of code to perform database operations. We need to only use annotations for performing database operations.

### Do you want to work on the issue?

Yes, I would like to work on the issue.

**Comment by geekanamika** [comment]
@arundhati24 It is a issue that can only be handled during a development lifecycle. Going by prior session discussion , include it in proposal & you won't need to create an issue for it. :)

**Comment by arundhati24** [comment]
@geekanamika  It would be great if you could please clarify what do you mean by development lifecycle here? :)

**Comment by geekanamika** [comment]
It can be closed & update room code is available in gsoc18-code branch.
