### ISSUE TITLE
Update an app to Material Design

### ISSUE THREAD

**Issue by pprathameshmore** [systers/malaria-app-android#288]
Update app as per Google material design

### Steps to reproduce the issue.
Write the steps to reproduce the issue (If applicable).

### Expected behavior.
An app must use the new material design for UI

### Your development environment
1. Device model - 
2. Android version - 

### LogCat
Provide LogCat in case of a crash.

**Comment by geekanamika** [comment]
@haroonshah2764 is working on UI. So, this can be closed.
