### ISSUE TITLE
Automate the apk building process.

### ISSUE THREAD

**Issue by m-murad** [systers/malaria-app-android#290]
## Description
As a developer,
I need to automate the process of building the apk,
so that we always have the apk with the latest code.

### Update [Required]
- [ ] Apk is automatically updated on the apk branch

## Estimation
1 hours

**Comment by geekanamika** [comment]
@m-murad Where can i learn about automating the apk build process, I would like to learn & implement it if it's available?

**Comment by m-murad** [comment]
@geekanamika 
Didn't see the comment until I sent the PR.

You can implement the same for `firstaid-android` or `realtrack-android` or `peacetrack-android` project. If you need help please let me know.
