### ISSUE TITLE
Fix Lint Errors

### ISSUE THREAD

**Issue by geekanamika** [systers/malaria-app-android#291]
### Lint Errors
Currently, Project contains Lint issues due to which Travis build was failing with build script `gradlew build`

### Steps to reproduce the issue.
1. Used `./gradlew lint` to check all lint issues
2. Solve each lint issues under `correctness` subtag

### Expected behaviour.
Solve the lint issue so that there will be no lint error under `correctness` errors.

### Build Report
![screenshot from 2018-04-18 23-02-42](https://user-images.githubusercontent.com/16922933/38948397-1cf6dd3e-435d-11e8-8a30-eaadb828c185.png)

### Do you want to work on the issue?
Yes

**Comment by geekanamika** [comment]
@m-murad Can I work on this issue?

**Comment by m-murad** [comment]
Sure, send a PR

**Comment by geekanamika** [comment]
I'll create separate multiple small first-timers issue for lint errors from updated code, closing this issue.
