### ISSUE TITLE
Add Travis CI for maintaining quality of incoming code 

### ISSUE THREAD

**Issue by r00pal** [systers/malaria-app-android#301]
## Description
As a developer,
I need continuous integration of the updated code
so that build process becomes easier and reliable.

## Definition of Done
- [ ] Travis CI dashboard is visible.
- [ ] Approval by 1 mentor.

## Estimation
1 hr

**Comment by geekanamika** [comment]
@roopalJazz Master branch already contains Travis & it's working. 
![image](https://user-images.githubusercontent.com/16922933/39827890-ee9b99ea-53d6-11e8-9309-2892e6849df1.png)
