### ISSUE TITLE
Making color scheme constant in the app

### ISSUE THREAD

**Issue by yatri1609** [systers/malaria-app-android#307]
Right now in the app shades of brown, green and pink are used. Rather than that it will be nice if we could stick to either shades of brown and pink. Also make the fonts used in the app constant. So that it looks more better and appealing to use.

I would like to work on the UI of this app.

**Comment by m-murad** [comment]
@yatri1609
Great, can you share screenshot of some changes that you would like to make.

**Comment by yatri1609** [comment]
Sure I'll make the changes and send the screenshots

**Comment by yatri1609** [comment]
Hey, these are the few changes I would like to make so that the app looks more even along with this I would also like to change the bottom buttons into side bar for which I will be opening another Issue.

![screenshot_2018-05-19-00-49-39-457_com peacecorps malaria](https://user-images.githubusercontent.com/34381723/40253887-12424a68-5aff-11e8-9656-912eee79d31b.png)
![screenshot_2018-05-19-00-49-42-822_com peacecorps malaria](https://user-images.githubusercontent.com/34381723/40253888-12af2ef8-5aff-11e8-80c2-58aa32f2e882.png)
![screenshot_2018-05-19-00-50-00-074_com peacecorps malaria](https://user-images.githubusercontent.com/34381723/40253889-12f39840-5aff-11e8-8fcd-8e79e77bc35b.png)
![screenshot_2018-05-19-00-50-11-463_com peacecorps malaria](https://user-images.githubusercontent.com/34381723/40253891-13344dae-5aff-11e8-9d1b-db1ed80eac88.png)

@m-murad Please have a look and tell me if I should proceed or not.

**Comment by geekanamika** [comment]
@yatri1609 There'll be alot of changes in malaria-android in GSoC with respect to UI/UX(idea is to shift to material-design). @haroonshah2764 is working on mockups & I'll implement as per discussion. You should discuss in #malaria channel in slack & work on Mockups?? 
Take reference from iOS too : https://youtu.be/tyM1Z8KWVF4?t=10m11s

**Comment by yatri1609** [comment]
@geekanamika Sure I would like to work on mockups and discuss on channel about the idea I have regarding the UI/UX of the app. Thank you . :+1:

**Comment by geekanamika** [comment]
Color scheme is constant in application now, closing this issue.
