### ISSUE TITLE
Add side bar instead of the bottom panel buttons

### ISSUE THREAD

**Issue by yatri1609** [systers/malaria-app-android#309]
I would like to convert the bottom panel buttons into the side bar so that it becomes easy for the person to use.
I would like to include:
- All the bottom panel button function
- Help and Feedback
- About Us
- Submit Issue 

Please see to this so that we can implement it.

**Comment by manishakeim** [comment]
@yatri1609 This kind of changes should be first discussed on slack project channel and you should take at least approval from 1 mentor.

**Comment by manishakeim** [comment]
These kinds of UI/UX changes are being handled in GSoC 2018. So closing this issue.
