### ISSUE TITLE
 PMD code rule violations.

### ISSUE THREAD

**Issue by haroonshah2764** [systers/malaria-app-android#314]
The project has around 144 PDM rule violations. Some of them are 

- [ ] Unused import in `BadgeRoomTest.java` at line 11
- [ ] Unused import in `MedicineStoreTest.java` at line 11
- [ ] Unused import in `MythFactGameTest.java` at line 10
- [ ] Unused import in `NewHomeActivityTest.java` at line 3
- [ ] Unused import in `NewHomeActivityTest.java` at line 5
- [ ] Unused import in `NewHomeActivityTest.java` at line 6
- [ ] Unused import in `NewHomeActivityTest.java` at line 13
- [ ] Unused import in `RapidFireGameTest.java` at line 11
- [ ] Unused import in `UserProfileTest.java` at line 11
- [ ] Avoid printStackTrace() in `MalariaDatabaseTest.java` at line 49
- [ ] Avoid printStackTrace() in `MalariaDatabaseTest.java` at line 396
- [ ] Avoid printStackTrace() in `DayFragmentActivity.java` at line 88
- [ ] Avoid printStackTrace() in `DayFragmentActivity.java` at line 285
- [ ] field name indicates a constant but its modifiers do not in `DayFragmentActivity.java` at line 38
- [ ] No need to call String.valueOf to append to a string in `DayFragmentActivity.java` at line 98
- [ ] Avoid using if...else statements without curly braces in `DayFragmentActivity.java` at line 239
- [ ] Avoid using if...else statements without curly braces in `DayFragmentActivity.java` at line 380

We need to fix the PMD code rule violations.

**Comment by aayushinigam** [comment]
@roopalJazz Can I work on this?

**Comment by geekanamika** [comment]
@aayushinigam You can, yes.

**Comment by geekanamika** [comment]
There's one open `available` lint issues, closing this one(many of the errors above mentioned are either removed or file has been deleted itself).
