### ISSUE TITLE
Remove .idea directory from gsoc18-infra branch

### ISSUE THREAD

**Issue by geekanamika** [systers/malaria-app-android#316]
**Description**
As a developer, 
I need to remove .idea/ directory from `gsoc18-infra` branch
which was committed by mistake in one [commit](https://github.com/systers/malaria-app-android/commit/cfd6da26f24d4b6d0690ab5479b87897bd63cae4)

**Estimated Time**
2 hours

**Comment by isabelcosta** [comment]
@geekanamika which branch is this referring to? It would help to have this in the Issue information. Which branch has this, and to which branch should the PR be sent?

**Comment by geekanamika** [comment]
Forgot to add the branch name in the description, thanks @isabelcosta  :)
