### ISSUE TITLE
Add Issue Template & Pull request template

### ISSUE THREAD

**Issue by geekanamika** [systers/malaria-app-android#317]
As a contributor, 
I need Issue & PR template
so that I can explain the details easily.

Reference: [Issue template](https://github.com/systers/powerup-android/blob/develop/ISSUE_TEMPLATE.md) & [PR template](https://github.com/systers/powerup-android/blob/develop/PULL_REQUEST_TEMPLATE.md)

Estimated Time:
2 hours

**Comment by ananyaarun** [comment]
Hi @geekanamika !!  I would like to work on this . Where should the 2 templates be added , the main repo right ?

**Comment by geekanamika** [comment]
Yes, Take the reference from http://github.com/systers/powerup-android/

**Comment by m-murad** [comment]
Not a valid issue, templates are already present in `master` branch.

**Comment by geekanamika** [comment]
@m-murad Yes, I'm aware of it but default branch is `develop` which is behind `master` & I don't get Template when I click `new issue`. 
Can we update develop from master branch? @ExactlyMay told me to update `develop` as It's the default branch (about a month ago) Or we can change our `default branch` to `master` ?

**Comment by m-murad** [comment]
Sending files which are in the repo already doesn't make sense. What we need to do is complete merge master in develop. Then we will have all the files that we need. 

Anamika can you do that?

**Comment by geekanamika** [comment]
Yes, I can do it. Just making it clear, I've to create a PR from master branch to develop branch & resolve merge conflicts if any, right?

**Comment by m-murad** [comment]
Yes, do the following
1. Merge develop in master
2. Merge master in develop
At this point master = develop
3. Merge master or develop in gsoc18-infra
Then master = develop = gsoc18-infra

**Comment by geekanamika** [comment]
As per discussion with mentors in 1:1 session, closing this issue.
