### ISSUE TITLE
Making app adaptive for all screens and orientation

### ISSUE THREAD

**Issue by ankita-kalra** [systers/malaria-app-android#33]
Currently, the malaria android application is for limited screens and orientation. The XMLs are to be included for different screen sizes.

**Comment by InsectiousApp** [comment]
@ankita-kalra  Hii ankita , can you please elaborate it and how can I start working on it ...

**Comment by yatna** [comment]
I am working on this issue. Since, there are many layouts and for each layout many sizes , it may take a while.

**Comment by ankita-kalra** [comment]
@InsectiousApp The application should look even in big tablet screen, also for landscape orientation currently I have added scroll view, but the layout should be made adaptive.

**Comment by anubhakushwaha** [comment]
@yatna are you still working on this issue? can't see your PR by now,can I do it,incase you aren't.
@ankita-kalra please do let me know

**Comment by yatna** [comment]
Completed in GSoC 16 @chhavip Please close this one too.
