### ISSUE TITLE
Improve UI of user profile layout

### ISSUE THREAD

**Issue by geekanamika** [systers/malaria-app-android#339]
**Description**
As a developer, 
I need to shift current UI to new designed UI during GSoC period
so that It will follow material design guidelines.

**Mock up**
![userpage](https://user-images.githubusercontent.com/16922933/42731672-c07568ce-882f-11e8-90c2-370a87819999.jpeg)

**Estimated time**
24 hours

**Comment by r00pal** [comment]
@geekanamika can you also address #329 ?

**Comment by geekanamika** [comment]
@roopalJazz I've completed #215  in # 341. I've also updated colors.xml with the material palette colors in 341.(solves half of #307 ). 
I can take up rest issues once I've complete mvp & tests for malaria. 
Please have a look at #341
