### ISSUE TITLE
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.

### ISSUE THREAD

**Issue by pprathameshmore** [systers/malaria-app-android#342]
Description:
As a developer,
We need to replace all 'compile' with 'implementation' and 'API'.
It will be removed at the end of 2018.

![malaria app](https://user-images.githubusercontent.com/17108186/42823529-696e2bf6-89fb-11e8-9319-1b3ba926740e.JPG)

Estimated hours:
12 Hours.

**Comment by geekanamika** [comment]
Hey @pprathameshmore , please find the latest code in `gsoc18-code` branch. It has been updated & will be merged at the end of the GSoC period.

**Comment by pprathameshmore** [comment]
@geekanamika Okay!
