### ISSUE TITLE
Making the malaria app adaptive for other languages

### ISSUE THREAD

**Issue by Michaeldgeek** [systers/malaria-app-android#35]
@ankita-kalra : I would like to create a string XML file for French language.

**Comment by luckyman000786** [comment]
@anubhakushwaha @ankita-kalra Can I make it adoptive to more languages like French, German, Chinese etc.

**Comment by DipanshKhandelwal** [comment]
@prachi1210 @MeepyMay @saurabhjn76 @m-murad 
Would it be good if we have internationalization in the app ?

**Comment by geekanamika** [comment]
low priority issue, closing with open-later label.
