### ISSUE TITLE
Add Feature discover animation in Rapid fire/Myth vs Fact game

### ISSUE THREAD

**Issue by geekanamika** [systers/malaria-app-android#364]
## Description
As a developer, 
I need to inform user for the feature inside game
so that User will get information about game before playing it.

## Acceptance Criteria
- [ ] Use Google's material design guidelines
- [ ] Expected UI : https://github.com/KeepSafe/TapTargetViewd
- [ ] Comes only for the first time when playing game
- [ ] Can watch again from selecting menu option

## Definition of Done
- [ ] Approval by 2 mentors
- [ ] All of the required items are completed

## Estimated time
48 hours

**Comment by yatri1609** [comment]
@geekanamika Can I work on this issue? Since I had tried doing same for some of other apps. So I have experience about the same.

**Comment by geekanamika** [comment]
Hey @yatri1609 , I've implemented this feature already. Forgot to add `gsoc` label here. I'll be creating more issues in upcoming days :)

**Comment by yatri1609** [comment]
@geekanamika ohk cool np !

**Comment by geekanamika** [comment]
Code merged.
