### ISSUE TITLE
Shifting the project to gradle build platform

### ISSUE THREAD

**Issue by yatna** [systers/malaria-app-android#39]
The project needs to be shifted to a gradle build platform to ensure a greater stability and easy of developing. Gradle enjoys numerous benefits over the traditional build system.

**Comment by haddada** [comment]
I'am working on it

**Comment by yatna** [comment]
@haddada I have already done it for ankita-gsoc-v1 branch

**Comment by yatna** [comment]
You may do it for the others

**Comment by haddada** [comment]
@yatna I created a pull request to the master branch by mistake , 
should i create it for the other barnchs ?

**Comment by yatna** [comment]
Actually master and ankita-gsoc-v1 are only active these days... U may create it for the others..collaborators will review and merge them accordingly..

**Comment by ankita-kalra** [comment]
I had project offline in gradle build during GSoC. It ll be committed separately in gsoc-gradle-build branch. The current project structure will remain the same, because it can anyway be imported to Android Studio, so no issues with that and will have backward compatibility for others.
