### ISSUE TITLE
TripIndicatorFragmentActivity crashes

### ISSUE THREAD

**Issue by haddada** [systers/malaria-app-android#46]
the TripIndicatorFragmentActivity crashes when the user click add Items before adding Departure and Arrivale Date

**Comment by yatna** [comment]
This issue has been fixed with #13 which was later merged as #37

**Comment by haddada** [comment]
thank you @yatna ,so the master branch isn't the HEAD

**Comment by yatna** [comment]
@haddada The ankita-gsoc-v1 is much ahead of master. There may be certain bugs in master which have been fixed in ankita-gsoc-v1 branch. Also there are additional functionalities.
