### ISSUE TITLE
Adding hardcoded integers, strings to dimens.xml and strings.xml

### ISSUE THREAD

**Issue by medhach** [systers/malaria-app-android#47]
I would like to add all the hard coded dimensions and strings to dimens.xml and strings.xml

**Comment by anubhakushwaha** [comment]
@medhach Working on this?

**Comment by medhach** [comment]
@anubhakushwaha No, you can go ahead.

**Comment by HimanshuS01** [comment]
@anubhakushwaha can I work on this issue ?

**Comment by nitish1211** [comment]
@HimanshuS01 I'm already working on this please find another issue.

**Comment by HimanshuS01** [comment]
Hey @nitish1211 In issue #223 you are talking about placing all the hardcoded strings in R.strings(strings.xml) but in this issue( #47 ) we also have to place all the hardcoded integers into dimens.xml  .
If you don't mind can I work on the second one (adding hardcoded integers in dimens.xml).What's say?
Thanks :)

**Comment by nitish1211** [comment]
Okay sure. We'll split it. :)
You can do the `dimens.xml`
I'll do the `strings.xml`

**Comment by HimanshuS01** [comment]
@nitish1211 Sure :)

@anubhakushwaha @yatna @chhavip can I work on this issue? Thanks

**Comment by HimanshuS01** [comment]
@anubhakushwaha @chhavip @yatna can I send PR for this issue?

**Comment by anubhakushwaha** [comment]
Yeah go ahead.

**Comment by HimanshuS01** [comment]
Sure @anubhakushwaha .I will soon send the PR. Thanks :)

**Comment by geekanamika** [comment]
duplicate issue, #291  & #270
