### ISSUE TITLE
Condense all similar fragment layouts into one.

### ISSUE THREAD

**Issue by medhach** [systers/malaria-app-android#49]
For the fragment layouts related to the info-section, the text views can be made dynamic, by sending input from the Activity.class' side.
I would like to remove - 
1. effectiveness_fragment.xml
2. peace_corps_policy_fragment.xml
3. side_effects_npcv_fragment.xml
4.  side_effects_pcv_fragment.xml
5. side_effects_percentage_fragment.xml
6. volunteer_adherence_fragment.xml

I will add a new xml file - info_fragments.xml
and add similar views. I will create another class, which will take care of all the backend activity of sending and receiving the right data.

**Comment by ankita-kalra** [comment]
Hi @medhach , the current version of app has the way to send data to server using volley JSON library, also the data is stored in cache. I will add the requirements related to the Info Hub here.

Elaborate on the need of an extra activity.

**Comment by anubhakushwaha** [comment]
@medhach Working on this?

**Comment by medhach** [comment]
@anubhakushwaha Nope.
