### ISSUE TITLE
SecondAnalyticFragment

### ISSUE THREAD

**Issue by Yasic** [systers/malaria-app-android#52]
There are a lot of error and some make the app crashed.I forked it and fix some bug.
The main error occurs in the getMonth() 
Calendar.getInstance().get(Calendar.YEAR) return the value of (month - 1), not the value of month,so there will be a error when we put the value to "month" array,the app will crash.
And I'm confused why it name the value of month "date",I fixed it,too.
Here is the url of my repo
https://github.com/Yasic/malaria-android
and here is the file of SecondAnalyticFragment
https://github.com/Yasic/malaria-android/blob/master/malaria-app-android/src/com/peacecorps/malaria/SecondAnalyticFragment.java

**Comment by ankita-kalra** [comment]
This doesn't fix, after this current month is showing to be May.
