### ISSUE TITLE
Added a ClickableSpan in DrugArrayAdapter which takes directly to the DrugSite 

### ISSUE THREAD

**Issue by anubhakushwaha** [systers/malaria-app-android#54]
What is the use of just displaying the drug sites name user would hardly take the courtesy to copy the link paste it in its search engine and read about it,instead a clickable span would lead it there directly.
Screenshots are below,I have already implemented it can I send a PR?
BEFORE:
![screenshot_2016-03-23-21-04-08](https://cloud.githubusercontent.com/assets/12814245/13995938/861d06f4-f151-11e5-8072-5b641e9c48c1.png)

AFTER:
![screenshot_2016-03-23-23-21-08](https://cloud.githubusercontent.com/assets/12814245/13995951/96f05512-f151-11e5-88dc-b6a963e61d36.png)

**Comment by anubhakushwaha** [comment]
@yatna @chhavip Is this an intended enhancement or a valid issue?

**Comment by chhavip** [comment]
yes, this is a valid requirement.

**Comment by anubhakushwaha** [comment]
@chhavip Can I send the PR for the same?

**Comment by HimanshuS01** [comment]
@anubhakushwaha @chhavip @yatna can I take up this issue  and send the PR for the same?
Thanks.

**Comment by anubhakushwaha** [comment]
@HimanshuS01 Yes go ahead.

**Comment by anubhakushwaha** [comment]
Closing. Fixed via #221
