### ISSUE TITLE
Notification should be set to autoCancel 

### ISSUE THREAD

**Issue by anubhakushwaha** [systers/malaria-app-android#56]
Notification Builder should be set to autoCancel for the convenience of the user. Though it just requires one line editing,it maybe be irritating for the user to swipe and remove it even though he has already clicked it.

**Comment by yatna** [comment]
@anubhakushwaha In fact, the ringtone does not stop even on swiping the notification. The user has to explicitly open the app and then close it to turn off the sound. This can be very irritating.

**Comment by anubhakushwaha** [comment]
@yatna yup I agree with you,don't you think we can include that too in our issue and remove it because at the end of the day it's the users we are serving.

**Comment by yatna** [comment]
@anubhakushwaha Sure.

**Comment by geekanamika** [comment]
Solving it as a part of #335
