### ISSUE TITLE
The Alarm stops as soon as the notification bar is clicked

### ISSUE THREAD

**Issue by anubhakushwaha** [systers/malaria-app-android#57]
As soon as the user reaches the TripAlarmActivity the alarm should stop as it may irritate the user.
We just need to stop the ringtone as soon as we reach the TripAlarmActivity. I have implemented this as well , can I send a PR for this?

**Comment by ankita-kalra** [comment]
send it

**Comment by anubhakushwaha** [comment]
@ankita-kalra  ma'am sent it.

**Comment by yatna** [comment]
Completed in GSoC16 @chhavip please close this one too.
