### ISSUE TITLE
Add a Splash screen at the beginning of the app

### ISSUE THREAD

**Issue by anubhakushwaha** [systers/malaria-app-android#58]
@ankita-kalra  Can I add a splash screen at the beginning of the app to give a brief view of the app to the user. I have designed a demo splash screen which will be availed to the user for about 5 seconds.
![screenshot_2016-03-30-16-00-56](https://cloud.githubusercontent.com/assets/12814245/14139504/2022563e-f691-11e5-858f-a2b53bfee607.png)

Animation View has also been included which zooms in and zooms out the image as well.

**Comment by ankita-kalra** [comment]
Can you add a gif here for the splash screen demo which you have prepared?

**Comment by anubhakushwaha** [comment]
![gif](https://cloud.githubusercontent.com/assets/12814245/14320622/65d13fae-fc33-11e5-807d-823e47d61990.gif)

@ankita-kalra ma'am something of this sort.
PS: it's hard taking the screenshots showing the flow.
If you want changes let me know :)

**Comment by pandilladivya** [comment]
@ankita-kalra @anubhakushwaha  @chhavip

Is someone working on this?
If not, I would like to take up this issue.

Kindly reply
Thank You :)

**Comment by chhavip** [comment]
I personally do not favor Splash Screens until the application required heavy background processing as it is an anti-pattern. http://cyrilmottier.com/2012/05/03/splash-screens-are-evil-dont-use-them/. Not sure if this should be done.

**Comment by anubhakushwaha** [comment]
Closing as of now.
