### ISSUE TITLE
Adding Intro Screens to the app

### ISSUE THREAD

**Issue by yatna** [systers/malaria-app-android#61]
Intro screens provides an introduction and gives the users information about the features of the application, when the application is opened for the very first time. I intend to add intro screens using the paolorotolo:appintro library, which creates intro screens with minimum amount of code.

**Comment by ankita-kalra** [comment]
Tutorial Screens will be built instead of intro screens. One of the students worked on it in Google code-in 2015. It needs to be tested and integrated. Something like this is implemented-
![84op4](https://cloud.githubusercontent.com/assets/2662871/14310672/dbad9f84-fc00-11e5-8a35-219bd9dcf85b.png)
