### ISSUE TITLE
Using Realm instead of Sqlite Database

### ISSUE THREAD

**Issue by anubhakushwaha** [systers/malaria-app-android#63]
I came across Realm a few weeks back,it is great with respect to database management as it highly optimizes the app. Using realm provides a better user experience and renders our app faster.

Some of the comparisons can be easily witnessed below.
![desk1](https://cloud.githubusercontent.com/assets/12814245/14230570/8ba71236-f97b-11e5-9acf-284f4630bda0.JPG)
![desk2](https://cloud.githubusercontent.com/assets/12814245/14230571/90cc1f36-f97b-11e5-911e-faff20c67346.JPG)
![desk3](https://cloud.githubusercontent.com/assets/12814245/14230572/94328624-f97b-11e5-81ce-709d5d2fbdc2.JPG)

Do the mentors agree to this and should I start working upon this? 
@ankita-kalra Please let e know as soon as possible so that I can start with .

**Comment by ankita-kalra** [comment]
Good Find. Start with Third Analytic Fragment Activity where the user is required to insert the data. We can compare the performance of the two versions in real time, to validate above.

**Comment by anubhakushwaha** [comment]
@ankita-kalra okay sure.

**Comment by vaibhavchellani** [comment]
Why was this issue closed ?

**Comment by anubhakushwaha** [comment]
@vaibhavchellani This needs a discussion with other mentors and not an intended issue as of now.Will reopen it with any future updates
