### ISSUE TITLE
Widget for Trip Reminder

### ISSUE THREAD

**Issue by ankita-kalra** [systers/malaria-app-android#64]
A widget with features can be created-
1. Shows the Date,Time and Destination of Trip
2. Edit button opens Trip Reminder form of Malaria App and user can edit entries .

**Comment by yatna** [comment]
I am working on this.

**Comment by yatna** [comment]
PR sent #75

**Comment by yatna** [comment]
Completed in GSoC16. @chhavip Please close this as well.
