### ISSUE TITLE
Widget for Pill Tracker

### ISSUE THREAD

**Issue by ankita-kalra** [systers/malaria-app-android#65]
Instead of opening the app for click on the check or cross button, we can have a widget which has tick, cross and edit button.

The functionalities can be like-
1.  Tick- Medicine Taken
2.  Cross- Medicine Not Taken
3.  Edit- Opens up the specific Day Analytic Page of the app, where we can edit the entry.

**Comment by Michaeldgeek** [comment]
@ankita-kalra  I am working on it.

**Comment by pandilladivya** [comment]
@ankita-kalra @yatna
Is this done?
If not can I work on this?

Thank you :)

**Comment by yatna** [comment]
Completed in GSoC 16 @chavvip can you please close this.
