### ISSUE TITLE
Bug in setNumDrugs() function

### ISSUE THREAD

**Issue by yatna** [systers/malaria-app-android#67]
If the arrival date of trip is set before the departure date, setNumDrugs() gave a negative result which means number of drugs needed for the trip are -ve. This is logically incorrect because the arrival date cannot ever be before the departure date. Hence,  a check mechanism needs to be added to check that the arrival date is not before the departure date.

**Comment by ankita-kalra** [comment]
you created a PR on this right?

**Comment by yatna** [comment]
Yes #45

**Comment by ankita-kalra** [comment]
Will be reviewing it.
