### ISSUE TITLE
Improving Trip Reminder Notifications

### ISSUE THREAD

**Issue by ankita-kalra** [systers/malaria-app-android#68]
The reminder which comes in notification has view checklist button currently.

Improvements which can be done-
1. Adding Edit Trip Button with View Checklist.
2. Edit Trip opens the Trip Indicator Filled form where user can change details.

**Comment by anubhakushwaha** [comment]
@ankita-kalra can I work upon this and send a PR?

**Comment by anubhakushwaha** [comment]
@ankita-kalra Resolved this issue.
Basically on clicking edit user gets the option of modifying the packing list which refreshes the listview and a new packing list is stored in the database.
![www gifcreator me_vrynrh](https://cloud.githubusercontent.com/assets/12814245/14404082/26129010-fe8c-11e5-9461-06e0900b0cf6.gif)

Gif of which is uploaded below. Can I send a PR for this?
