### ISSUE TITLE
Testing Calendar and Modification of Calendar Header

### ISSUE THREAD

**Issue by ankita-kalra** [systers/malaria-app-android#69]
Grid Cell Adapter is used for making the Calendar in the Third Analytic Fragment Activity. Sometimes it takes time to load the calendar, because each grid cell is initialized to make the calendar. This can be compared against a custom calendar view library or modification of existing Android Calendar API can be done, to decrease the processing load.

Currently image is used for showing the weekdays on header of calendar. It is not a vector image, so not adapts to the size. 

Ways it can be taken care of-
1. Creating grid cells for week days.
2. Using custom calendar view library.

**Comment by yogeshbalan** [comment]
@ankita-kalra , I am working on it.

**Comment by yogeshbalan** [comment]
@ankita-kalra , I have solved this issue by taking 2nd choice of yours. I have added [Caldroid](https://github.com/roomorama/Caldroid) library to implement calendarView. I will update the documentation of implementation in PR.
here the screenshot of it.
![screenshot_20160413-131548](https://cloud.githubusercontent.com/assets/6052857/14486754/37571e3e-017c-11e6-8dc5-1b21ba2ff5b6.png)
![screenshot_20160413-131553](https://cloud.githubusercontent.com/assets/6052857/14486780/58d64616-017c-11e6-993d-e4db383a9dd5.png)

**Comment by yogeshbalan** [comment]
Here's the APK with caldroid changes.
[Malaria Prevention_1.0.apk.zip](https://github.com/systers/malaria-app-android/files/216625/Malaria.Prevention_1.0.apk.zip)

**Comment by ankita-kalra** [comment]
Have you compared the performance?

Adding a new library without major performance change might be taxing.

Here's the APK with caldroid changes.
Malaria Prevention_1.0.apk.zip
<https://github.com/systers/malaria-app-android/files/216625/Malaria.Prevention_1.0.apk.zip>

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/systers/malaria-app-android/issues/69#issuecomment-209294817>

**Comment by yogeshbalan** [comment]
Hi @ankita-kalra , 
I have ran some performance test  on both apps. Here are the results :- 
- I ran **GPU rendering test** on **ThirdAnalyticFragment** (The previous implementation) here's the result 
![rsz_screenshot_without_caldroid](https://cloud.githubusercontent.com/assets/6052857/14569720/06f4561a-035e-11e6-8450-387da75bfc19.png)

 Then I ran same test on **CalenderViewActivity** (The new implementation) here's the result 
  ![rsz_screenshot_20160414-132737](https://cloud.githubusercontent.com/assets/6052857/14569880/0227ac1c-035f-11e6-8c88-f29ec765b740.png)

 - Thus from above test, this can be concluded that the overall **custom view drawing** time, time spent in **transferring resources to the render thread**, time spent by **Android's 2D renderer** and time the **CPU is waiting for the GPU to finish its work** is lesser in new CalnderView. I gathered detailed information about these color from this link [Profiling GPU Rendering](http://developer.android.com/tools/performance/profile-gpu-rendering/index.html)

- Then I ran **CPU load test** from android studio on **ThirdAnalyticFragment** (The previous implementation) here's the result 
![without_caldroid](https://cloud.githubusercontent.com/assets/6052857/14570509/40801b90-0362-11e6-84e4-934f29839276.png)
  Then I ran same test on **CalenderViewActivity** (The new implementation) here's the result 
  ![with_caldroid](https://cloud.githubusercontent.com/assets/6052857/14570532/71a33acc-0362-11e6-838f-767b55ee13cc.png)
 - The spikes are showing CPU usage while swiping. Each swipe shows CPU usage to inflate new month. The margin between the new and old implementation is not much but surely noticeable from the users perspective.

- The **GPU Overdraw** shows 3x-4x OverDraw on both new and old implementation. Hence no changes in this criteria. 

**I hope this would help or else I will have to do more rigorous UI testing on these two activities**

**Comment by geekanamika** [comment]
In updated master branch, we don't this screen. We can open this issue later once existing bugs are resolved.
