### ISSUE TITLE
Improving and Proper Updating of GraphView

### ISSUE THREAD

**Issue by ankita-kalra** [systers/malaria-app-android#70]
Many grids are made on the background if entered data is scarce. Needs to be taken care of. Also when single data point is there then a constant line should appear.

Smooth updating of graphview is required. Editing data in the Day Analytic Fragment Activity, and returning to second analytic fragment activity does not update the graph view.

**Comment by top-gun007** [comment]
is this issue fixed?

**Comment by yatna** [comment]
Fixed in GSoC16 . @chhavip Please close this issue as well .
