### ISSUE TITLE
No Touch Feedback in Buttons and EditText 

### ISSUE THREAD

**Issue by yogeshbalan** [systers/malaria-app-android#76]
A certain touch feedback should be provided in android app for assuring user that they are engaging with that particular UI element. A better UX approach will suggest to provide touch feedback whether user hits a **Button**, **EditText** etc. The feedback can be in the following form :- 
- Color change of button/editText drawable 
- Popup of button (A slight increase in size of drawable with little increase in alpha)

**Comment by anubhakushwaha** [comment]
@yogeshbalan hi, what about a ripple effect ,it works directly using ripple Drawable in lollipop and in pre-lollipop it can be implemented using balysv/material-ripple library,hope I was of some help.

**Comment by yogeshbalan** [comment]
@anubhakushwaha Since the app is not following **Material Design Guidelines**, I didn't mention ripple as an option to provide feedback. Also adding another module just for adding ripple would not be a good practice. IMO, just modifying background drawable would do the trick. What's say? 

P.S : I really appreciate the suggestion :+1:

**Comment by anubhakushwaha** [comment]
@yogeshbalan Yup great idea :+1:

**Comment by shamathmika** [comment]
@yogeshbalan @anubhakushwaha 
Is this done?

**Comment by chhavip** [comment]
@shamathmika no it hasnt been done yet

**Comment by free4murad** [comment]
@anubhakushwaha 
Can I work on this

**Comment by anubhakushwaha** [comment]
Before you proceed,how are you planning to do it?

**Comment by free4murad** [comment]
I suggest changing the color of the views by listening to motion events on the views.

**Comment by anubhakushwaha** [comment]
Go ahead :+1:

**Comment by geekanamika** [comment]
It will be solved as a part of #329
