### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by rosariorobinson** [systers/malaria-app-android#8]
Date format in the app should be MM/DD/YYYY.

**Comment by ankita-kalra** [comment]
Format changed in my latest commit. 

https://github.com/systers/malaria-app-android/commits/ankita-gsoc-v1

Commit: @de3ccd3

![device-2015-08-20-222916](https://cloud.githubusercontent.com/assets/2662871/9399997/6d367566-47d9-11e5-8487-b98c0a0bd807.png)
![device-2015-08-20-223103](https://cloud.githubusercontent.com/assets/2662871/9399998/6d3b072a-47d9-11e5-981f-8c59662fbbbc.png)
