### ISSUE TITLE
Update ReadME

### ISSUE THREAD

**Issue by MeepyMay** [systers/malaria-app-android#88]
Hi @ankita-kalra  ... @rosariorobinson and I are trying to prepare for GHC Open source day and we need help with the ReadME. Can you help with updating the ReadME with more specifics on setup? The goal is to environment ready on a USB in case there are WiFi issues. 

Is it possible to have README updated by Friday or Saturday (10/14 or 10/15 respectively) at the latest? We really need your help.

Please use this issue to update us on this task.

**Comment by MeepyMay** [comment]
@yatna Can you update the ReadMe to include **detailed** instructions on setting up the environment? Something similar to the [Development section on Malaria iOS](https://github.com/systers/malaria-app-ios#development).

**Comment by yatna** [comment]
@MeepyMay Sure, started working on it.

**Comment by yatna** [comment]
@MeepyMay To build the gradle version of the app, you need to merge my PR #84 into the code base. After that the project can be cloned and opened in android studio using the ankita-gsoc-gradlebuild branch. I can add these steps to build the project in the README.md but they will only work after the PR is merged.

**Comment by yatna** [comment]
@MeepyMay Meanwhile you can build the adt version of the application (which is how I build it before this GSoC). This is a bit length, but it worked for me. 
This doc was created by Ankita last year, I have modified it as required. https://docs.google.com/document/d/18LdXPewdUepmq9sEJMu7yHoUpwRAAaaDwHhnu08DOTY/edit?usp=sharing
