### ISSUE TITLE
Hardcoding the string in string.xml file.

### ISSUE THREAD

**Issue by saketkumar95** [systers/malaria-app-android#99]
There are many values / string which are hardcoded in the .xml file. It should be stored in the single file so that it can be accessed to the same text from anywhere in the app.
I would send the PR soon when i get assigned.

@MeepyMay Can i work on this?

**Comment by Ebaneck** [comment]
+1 If we might support multi language some day soon

**Comment by saketkumar95** [comment]
Can i just hard code the values in dimens.xml and strings.xml ?

**Comment by yatna** [comment]
Issue already exists #47 . @chhavip Please close this issue . Thank You :-)
